name = "@metorial/code-workspace"
group = "oss"

[test.e2e]
start = ["vite --port 3302 --host 0.0.0.0"]

[dev]
prepare = ["setup_vscode"]
run = ["vite --port 3302 --host 0.0.0.0"]

[[dev.expose]]
port = 3302
