name = "@metorial/code-workspace"
group = "oss"

[test.e2e]
prepare = []
start = ["test:start-e2e"]

[dev]
prepare = ["setup_vscode"]
run = ["dev:start"]

[endpoints.web]
port = 3302
env = [{ key = "PORT", value = "{{BIND_PORT}}" }]
