name = "@metorial/code-workspace"
group = "oss"

[test.e2e]
start = ["vite --port \"$PORT\" --host 0.0.0.0"]

[dev]
prepare = ["setup_vscode"]
run = ["vite --port \"$PORT\" --host 0.0.0.0"]

[endpoints.web]
port = 3302
env = [{ key = "PORT", value = "{{PORT}}" }]
