name: Build and Publish Hub

on:
  push:
    branches:
      - main
    paths:
      - 'src/systems/slates/apps/hub/**'
      - 'src/systems/slates/packages/**'
      - 'src/systems/slates/clients/**'
      - 'src/systems/_clients/slates/**'
      - 'src/systems/slates/.github/workflows/publish-hub.yml'
      - '.github/workflows/system-build-image.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/systems/slates/apps/hub/**'
      - 'src/systems/slates/packages/**'
      - 'src/systems/slates/clients/**'
      - 'src/systems/_clients/slates/**'
      - 'src/systems/slates/.github/workflows/publish-hub.yml'
      - '.github/workflows/system-build-image.yml'

jobs:
  build-and-publish-docker:
    uses: ./.github/workflows/system-build-image.yml
    secrets: inherit
    with:
      image_name: metorial/slates-hub
      docker_context: ./src/systems/slates/apps/hub
      dockerfile: ./src/systems/slates/apps/hub/Dockerfile
