import { db } from '@metorial/db';
import { createQueue } from '@metorial/queue';
import {
  skillMergeRequestInclude,
  skillMergeRequestInternalService
} from '../internal/skillMergeRequestInternal';
import { getCanonicalSkillPairKey } from '../lib/mergeLock';
import { skillMergeRequestService } from '../services/skillMergeRequest';
export let skillForkSyncQueue = createQueue<{
  skillForkSyncId: string;
}>({
  name: 'cargo/skill/fork-sync',
  workerOpts: {
    concurrency: 5
  }
});

export let enqueueSkillForkSync = async (d: { skillForkSyncId: string }) => {
  await skillForkSyncQueue.add(d, {
    id: `skillForkSync:${d.skillForkSyncId}`
  });
};

export let processSkillForkSyncJob = async (d: { skillForkSyncId: string }) => {
  let sync = await db.skillForkSync.findUnique({
    where: { id: d.skillForkSyncId },
    include: {
      forkSkill: {
        include: {
          store: true
        }
      },
      upstreamSkill: {
        include: {
          store: true
        }
      },
      createdByResourceActor: true,
      generatedMergeRequest: {
        include: skillMergeRequestInclude
      },
      project: true,
      instance: true
    }
  });
  if (!sync || !['pending', 'processing', 'action_required'].includes(sync.status)) {
    return null;
  }

  let activePairKey = getCanonicalSkillPairKey(sync.forkSkillOid, sync.upstreamSkillOid);
  try {
    let claimed = await db.skillForkSync.updateMany({
      where: {
        id: sync.id,
        status: {
          in: ['pending', 'processing', 'action_required']
        }
      },
      data: {
        status: 'processing',
        error: null,
        processingStartedAt: sync.processingStartedAt ?? new Date()
      }
    });
    if (claimed.count !== 1) return null;

    let mergeRequest = sync.generatedMergeRequest;
    if (!mergeRequest) {
      mergeRequest = await skillMergeRequestInternalService.createDirectedSkillMergeRequest({
        project: sync.project,
        instance: sync.instance,
        sourceSkillId: sync.upstreamSkill.id,
        targetSkillId: sync.forkSkill.id,
        authorization: {
          type: 'privileged',
          resourceActor: sync.createdByResourceActor ?? undefined
        },
        title: `Sync ${sync.upstreamSkill.name ?? 'upstream'} into ${sync.forkSkill.name ?? 'fork'}`,
        description: 'Generated by fork synchronization',
        direction: 'upstream_to_fork',
        returnNullOnNoChanges: true,
        skillForkSyncId: sync.id
      });
    }

    if (!mergeRequest) {
      return await db.skillForkSync.update({
        where: { id: sync.id },
        data: {
          status: 'completed',
          activePairKey: null,
          error: null,
          completedAt: new Date()
        }
      });
    }

    let unresolvedCount = await db.skillMergeRequestItem.count({
      where: {
        skillMergeRequestOid: mergeRequest.oid,
        status: 'unresolved'
      }
    });
    if (unresolvedCount > 0) {
      return await db.skillForkSync.update({
        where: { id: sync.id },
        data: {
          status: 'action_required',
          error: mergeRequest.mergeError,
          actionRequiredAt: new Date()
        }
      });
    }

    if (mergeRequest.status === 'open') {
      await skillMergeRequestService.performSkillMergeRequest({
        project: sync.project,
        instance: sync.instance,
        mergeRequest,
        authorization: {
          type: 'privileged',
          resourceActor: sync.createdByResourceActor ?? undefined
        }
      });
    }

    return await db.skillForkSync.findUnique({
      where: { id: sync.id }
    });
  } catch (err) {
    let error = err instanceof Error ? err.message : 'Fork synchronization failed';
    let linkedRequest = await db.skillMergeRequest.findFirst({
      where: {
        generatedForkSync: {
          id: sync.id
        }
      }
    });
    let actionRequired = linkedRequest?.status === 'open';
    await db.skillForkSync.update({
      where: { id: sync.id },
      data: {
        status: actionRequired ? 'action_required' : 'failed',
        activePairKey: actionRequired ? activePairKey : null,
        error,
        actionRequiredAt: actionRequired ? new Date() : undefined,
        failedAt: actionRequired ? undefined : new Date()
      }
    });
    throw err;
  }
};

export let skillForkSyncQueueProcessor = skillForkSyncQueue.process(async data => {
  await processSkillForkSyncJob(data);
});
