import { createIdGenerator, idType } from '@metorial/id';

export let ID = createIdGenerator({
  emailIdentity: idType.sorted('eid'),
  email: idType.sorted('eml'),

  user: idType.sorted('usr'),
  userSession: idType.sorted('uss'),

  organization: idType.sorted('org'),
  organizationMember: idType.sorted('ome'),
  organizationInvite: idType.sorted('oin'),
  organizationActor: idType.sorted('oac'),
  organizationInviteJoin: idType.sorted('oij'),

  project: idType.sorted('prj'),
  projectBrand: idType.sorted('pbr'),
  projectBrandUpdate: idType.sorted('pbu'),
  instance: idType.sorted('ins'),

  machineAccess: idType.sorted('mac'),
  apiKey: idType.sorted('apk'),
  apiKeySecret: idType.sorted('aks'),
  apiKeyExpiredEmailSend: idType.sorted('aes'),
  oauthApplication: idType.sorted('oap'),
  oauthInstallation: idType.sorted('oai'),
  oauthAuthorization: idType.sorted('oaa'),
  oauthAuthorizationRequest: idType.sorted('oar'),
  oauthToken: idType.sorted('otk'),
  serviceAccount: idType.sorted('sac'),
  serviceAccountCredential: idType.sorted('scc'),
  cliDevice: idType.sorted('cli'),
  cliAuth: idType.sorted('cla'),
  apiApplication: idType.sorted('aap'),
  fineGrainedKey: idType.sorted('fgk'),
  sessionClientSecretReference: idType.sorted('fgr'),
  accessTagPolicy: idType.sorted('atp'),

  filePurpose: idType.sorted('fpu'),
  file: idType.sorted('fil'),
  fileLink: idType.sorted('flk'),
  fileRef: idType.sorted('frf'),

  secretType: idType.sorted('sty'),
  secret: idType.sorted('sec'),
  secretStore: idType.sorted('sst'),
  secretEvent: idType.sorted('sce'),

  importedServerVendor: idType.sorted('iven'),
  importedServer: idType.sorted('isrv'),
  importedRepository: idType.sorted('irep'),

  serverListing: idType.sorted('sli'),
  serverListingCategory: idType.sorted('slca'),
  serverListingCollection: idType.sorted('slco'),
  serverListingUpdate: idType.sorted('slup'),

  serverConfigSchema: idType.sorted('scs'),
  serverVariantProvider: idType.sorted('svp'),

  server: idType.sorted('srv'),
  serverVariant: idType.sorted('sva'),
  serverVersion: idType.sorted('sve'),

  serverImplementation: idType.sorted('svi'),
  serverDeployment: idType.sorted('svd'),
  serverDeploymentConfig: idType.sorted('svdc'),
  serverDeploymentTemplate: idType.sorted('svdt'),

  serverRunner: idType.sorted('sru'),

  sessionMessage: idType.sorted('msg'),
  sessionEvent: idType.sorted('sev'),
  session: idType.sorted('ses'),
  sessionConnection: idType.sorted('sco'),
  serverSession: idType.sorted('srs'),
  serverRun: idType.sorted('srr'),
  serverRunErrorGroup: idType.sorted('sreg'),
  serverRunError: idType.sorted('sre'),
  serverAutoDiscoveryJob: idType.sorted('sadj'),
  serverOAuthSession: idType.sorted('soas'),
  serverOAuthSession_ClientSecret: idType.unsorted('soas_sec', 50),
  sessionServerDeployment: idType.sorted('ssd'),

  instanceServer: idType.sorted('isv'),

  profile: idType.sorted('prf'),
  profileUpdate: idType.sorted('prfu'),

  clientSecret: idType.sorted('cse'),

  oauthConnectionTemplate: idType.sorted('poct'),
  oauthConnection: idType.sorted('poc'),
  oauthConnectionProfile: idType.sorted('pocp'),
  oauthConnectionAuthAttempt: idType.sorted('poca'),
  oauthConnectionAuthAttempt_State: idType.unsorted('poca_state'),
  oauthConnectionAuthAttempt_ClientSecret: idType.unsorted('poca_sec', 50),
  oauthConnectionAuthToken: idType.sorted('potk'),
  oauthDiscoveryDocument: idType.sorted('pod'),
  oauthConnectionEvent: idType.sorted('poce'),
  oauthAutoRegistration: idType.sorted('poar'),
  oauthConfig: idType.sorted('pocf'),
  providerOAuthRegistrationError: idType.sorted('pore'),
  providerOAuthTakeout: idType.sorted('poto'),
  providerOAuthTakeIn: idType.sorted('poti'),
  providerOAuthTakeInVersion: idType.sorted('potiv'),

  customServer: idType.sorted('csv'),
  customServerVersion: idType.sorted('csvv'),
  customServerEvent: idType.sorted('csvev'),
  customServerDeployment: idType.sorted('csd'),
  customServerDeploymentStep: idType.sorted('csds'),
  lambdaServerInstance: idType.sorted('lsi'),
  managedServerTemplate: idType.sorted('mst'),
  remoteServerInstance: idType.sorted('rsi'),
  dockerServerInstance: idType.sorted('dsi'),

  codeBucket: idType.sorted('cbu'),
  codeBucketTemplate: idType.sorted('cbt'),

  magicMcpServer: idType.sorted('mgsr'),
  magicMcpServerSubspaceSession: idType.sorted('mgss'),
  magicMcpSession: idType.sorted('mgsn'),
  magicMcpToken: idType.sorted('mgtk'),
  magicMcpGroup: idType.sorted('mggr'),
  magicMcpServerDeployment: idType.sorted('mgsrd'),

  scmInstallation: idType.sorted('sci'),
  scmAccount: idType.sorted('sca'),
  scmRepo: idType.sorted('scr'),
  scmRepoWebhook: idType.sorted('scrw'),
  scmRepoPush: idType.sorted('scmp'),

  callback: idType.sorted('clb'),
  callbackHook: idType.sorted('cbh'),
  callbackTemplate: idType.sorted('clt'),
  callbackEvent: idType.sorted('cbe'),
  callbackSchedule: idType.sorted('cbs'),
  callbackEventProcessingAttempt: idType.sorted('cbep'),
  callbackPollingAttempt: idType.sorted('cbpa'),
  callbackInstallation: idType.sorted('cbi'),
  callbackNotification: idType.sorted('cbn'),
  callbackNotificationAttempt: idType.sorted('cbna'),
  callbackDestination: idType.sorted('cld'),

  serverConfigVault: idType.sorted('scv'),

  accessLimiter: idType.sorted('acl'),

  team: idType.sorted('tm'),
  teamProject: idType.sorted('tmp'),
  teamMember: idType.sorted('tmm'),

  accessRole: idType.sorted('arl'),
  accessRoleVersion: idType.sorted('arv'),
  accessPolicy: idType.sorted('apl'),
  accessPolicyVersion: idType.sorted('apv'),
  accessPolicyRole: idType.sorted('apr'),
  accessPolicyProject: idType.sorted('app'),
  accessPolicyInstance: idType.sorted('api'),
  accessPolicyAssignment: idType.sorted('apa'),

  ssoTenant: idType.sorted('ssot'),
  ssoUser: idType.sorted('ssou'),

  consumerSurface: idType.sorted('csf'),
  consumerAuthTenant: idType.sorted('cot'),
  consumerAuthExchange: idType.sorted('cae'),
  consumer: idType.sorted('cng'),
  instanceConsumer: idType.sorted('cns'),
  consumerProfile: idType.sorted('cop'),
  consumerSession: idType.sorted('csn'),
  consumerSurfaceAuthFactor: idType.sorted('csaf'),
  consumerAuthCode: idType.sorted('cac'),
  consumerSurfaceMagicMcpGroupAccess: idType.sorted('csmg'),
  consumerGroup: idType.sorted('cog'),
  consumerAccess: idType.sorted('coa'),
  consumerAccessRequest: idType.sorted('coar'),
  consumerServerRequest: idType.sorted('csr'),
  consumerProviderSetupSessionBinding: idType.sorted('cpsb'),
  providerTemplate: idType.sorted('ptm'),

  portal: idType.sorted('ptl')
});
