import { db } from '@metorial/db';
import { createQueue } from '@metorial/queue';
import { CargoSkillLimitError } from '../../lib/limits';
import { applyMarketplace } from '../../serializers/marketplace';
import { applyPlugin } from '../../serializers/plugin';
import { applySkill } from '../../serializers/skill';
import { getSyncItemKey, getSyncTaskItemKey } from './_lib/item';
import { appendSkillDestinationSyncLog } from './_lib/logs';
import { createTaskManager, type SyncTask } from './_lib/task';
import { syncProcessQueue } from './process';
import { syncReconcileQueue } from './reconcile';

export let syncCollectQueue = createQueue<{
  skillDestinationSyncId: string;
  skillRepositoryId?: string;
}>({
  name: 'cargo/skill/sync/collect',
  workerOpts: {
    concurrency: 10
  }
});

let getSyncTaskLabel = (
  task: SyncTask,
  names: {
    marketplaces: Map<string, string>;
    plugins: Map<string, string>;
    skills: Map<string, string>;
  },
  existingItemKeys: Set<string>
) => {
  let itemKey = getSyncTaskItemKey(task);
  let action =
    task.action === 'delete' ? 'Remove' : existingItemKeys.has(itemKey) ? 'Update' : 'Add';

  if (task.type === 'marketplace') {
    return `${action} marketplace ${names.marketplaces.get(task.skillMarketplaceId) ?? task.skillMarketplaceId}`;
  }

  if (task.type === 'plugin') {
    return `${action} plugin ${names.plugins.get(task.skillPluginId) ?? task.skillPluginId}`;
  }

  return `${action} skill ${names.skills.get(task.skillId) ?? task.skillId} in plugin ${
    names.plugins.get(task.skillPluginId) ?? task.skillPluginId
  }`;
};

let getSyncPrMetadata = (d: {
  destination: {
    skillMarketplace?: { name: string | null; id: string } | null;
    skillPlugin?: { name: string | null; id: string } | null;
  };
  tasks: SyncTask[];
  names: {
    marketplaces: Map<string, string>;
    plugins: Map<string, string>;
    skills: Map<string, string>;
  };
  existingItemKeys: Set<string>;
}) => {
  let target = d.destination.skillMarketplace
    ? `marketplace ${d.destination.skillMarketplace.name ?? d.destination.skillMarketplace.id}`
    : d.destination.skillPlugin
      ? `plugin ${d.destination.skillPlugin.name ?? d.destination.skillPlugin.id}`
      : 'skill destination';

  let title = `Update ${target}`;
  let taskLines = d.tasks.map(
    task => `- ${getSyncTaskLabel(task, d.names, d.existingItemKeys)}`
  );

  return {
    prName: title,
    prDescription: [
      `Skills linked to the '${target}' marketplace were updated in Metorial. This PR synchronizes the following changes:`,
      '',
      ...taskLines,
      '',
      `<sub>This PR/MR was automatically generated by Metorial.</sub>`
    ].join('\n'),
    commitMessage: title
  };
};

let getSyncTaskNames = async (tasks: SyncTask[]) => {
  let marketplaceIds = tasks.flatMap(task =>
    task.type === 'marketplace' ? [task.skillMarketplaceId] : []
  );
  let pluginIds = tasks.flatMap(task =>
    task.type === 'plugin' || task.type === 'skill' ? [task.skillPluginId] : []
  );
  let skillIds = tasks.flatMap(task => (task.type === 'skill' ? [task.skillId] : []));

  let [marketplaces, plugins, skills] = await Promise.all([
    marketplaceIds.length
      ? db.skillMarketplace.findMany({
          where: { id: { in: [...new Set(marketplaceIds)] } },
          select: { id: true, name: true }
        })
      : [],
    pluginIds.length
      ? db.skillPlugin.findMany({
          where: { id: { in: [...new Set(pluginIds)] } },
          select: { id: true, name: true }
        })
      : [],
    skillIds.length
      ? db.skill.findMany({
          where: { id: { in: [...new Set(skillIds)] } },
          select: { id: true, name: true }
        })
      : []
  ]);

  return {
    marketplaces: new Map(
      marketplaces.map(marketplace => [marketplace.id, marketplace.name] as [string, string])
    ),
    plugins: new Map(plugins.map(plugin => [plugin.id, plugin.name] as [string, string])),
    skills: new Map(
      skills.map(skill => [skill.id, skill.name ?? 'Untitled skill'] as [string, string])
    )
  };
};

let failSyncForLimitError = async (d: { skillDestinationSyncId: string; error: unknown }) => {
  if (!(d.error instanceof CargoSkillLimitError)) return false;

  await db.skillDestinationSync.updateMany({
    where: {
      id: d.skillDestinationSyncId,
      status: 'processing'
    },
    data: {
      status: 'failed',
      completedAt: new Date()
    }
  });
  await appendSkillDestinationSyncLog(d.skillDestinationSyncId, d.error.message);
  return true;
};

export let syncCollectQueueProcessor = syncCollectQueue.process(async data => {
  let sync = await db.skillDestinationSync.findUnique({
    where: { id: data.skillDestinationSyncId },
    include: {
      destination: {
        include: {
          skillMarketplace: true,
          skillPlugin: true
        }
      }
    }
  });
  if (!sync || sync.status !== 'processing') return;

  await appendSkillDestinationSyncLog(
    data.skillDestinationSyncId,
    'Preparing content updates.'
  );

  let currentItems = await db.skillDestinationItem.findMany({
    where: { destinationOid: sync.destination.oid },
    include: { skill: true, skillPlugin: true, skillMarketplace: true }
  });

  let taskManager = createTaskManager(currentItems);
  let currentItemsByKey = new Map(currentItems.map(item => [getSyncItemKey(item), item]));
  let existingItemKeys = new Set(currentItemsByKey.keys());

  let getSerializerHash = async <Input, InitResult>(
    serializer: {
      init: (input: Input) => Promise<InitResult>;
      getHash: (input: Input, initResult: InitResult) => Promise<string>;
    },
    input: Input
  ) => {
    try {
      let initResult = await serializer.init(input);
      return await serializer.getHash(input, initResult);
    } catch (error) {
      if (
        await failSyncForLimitError({
          skillDestinationSyncId: data.skillDestinationSyncId,
          error
        })
      ) {
        return null;
      }

      throw error;
    }
  };

  let getCurrentMarketplaceItem = (marketplaceId: string) =>
    currentItemsByKey.get(`marketplace:${marketplaceId}`);

  let getCurrentPluginItem = (pluginId: string) => currentItemsByKey.get(`plugin:${pluginId}`);

  let getCurrentSkillItem = (d: { skillId: string; skillPluginId: string }) =>
    currentItemsByKey.get(`skill:${d.skillId}:${d.skillPluginId}`);

  if (sync.destination.skillMarketplace) {
    let marketplace = await db.skillMarketplace.findFirst({
      where: { oid: sync.destination.skillMarketplace.oid, status: 'active' },
      include: {
        skillConfiguration: true,
        plugins: {
          where: {
            status: 'active',
            skillPlugin: {
              status: 'active'
            }
          },
          include: {
            skillConfiguration: true,
            skillPlugin: {
              include: {
                skillConfiguration: true,
                skillPluginSkills: {
                  where: {
                    status: 'active',
                    skill: {
                      status: 'active'
                    }
                  },
                  include: {
                    skill: true,
                    skillConfiguration: true
                  }
                }
              }
            }
          }
        }
      }
    });

    if (marketplace) {
      let marketplaceHash = await getSerializerHash(applyMarketplace, {
        skillMarketplace: marketplace
      });
      if (!marketplaceHash) return;
      let currentMarketplaceItem = getCurrentMarketplaceItem(marketplace.id);

      if (currentMarketplaceItem?.hash === marketplaceHash) {
        taskManager.keepItem({ skillMarketplace: marketplace });
      } else {
        taskManager.addOrUpdateItem({ skillMarketplace: marketplace });
      }

      for (let marketplacePlugin of marketplace.plugins) {
        let skillPlugin = {
          ...marketplacePlugin.skillPlugin,
          skills: marketplacePlugin.skillPlugin.skillPluginSkills
        };
        let skillMarketplacePlugin = {
          ...marketplacePlugin,
          plugin: skillPlugin
        };

        let pluginHash = await getSerializerHash(applyPlugin, {
          skillPlugin,
          skillMarketplace: marketplace,
          skillMarketplacePlugin
        });
        if (!pluginHash) return;
        let currentPluginItem = getCurrentPluginItem(skillPlugin.id);

        if (currentPluginItem?.hash === pluginHash) {
          taskManager.keepItem({ skillPlugin });
        } else {
          taskManager.addOrUpdateItem({ skillPlugin });
        }

        for (let skillPluginSkill of skillPlugin.skillPluginSkills) {
          let skillHash = await getSerializerHash(applySkill, {
            skill: skillPluginSkill.skill,
            skillPlugin,
            skillPluginSkill,
            skillMarketplace: marketplace,
            skillMarketplacePlugin
          });
          if (!skillHash) return;
          let currentSkillItem = getCurrentSkillItem({
            skillId: skillPluginSkill.skill.id,
            skillPluginId: skillPlugin.id
          });

          if (currentSkillItem?.hash === skillHash) {
            taskManager.keepItem({
              skill: skillPluginSkill.skill,
              skillPlugin
            });
          } else {
            taskManager.addOrUpdateItem({
              skill: skillPluginSkill.skill,
              skillPlugin
            });
          }
        }
      }
    } else {
      let currentMarketplaceItem = currentItems.find(
        item => item.skillMarketplace?.id === sync.destination.skillMarketplace?.id
      );

      if (currentMarketplaceItem?.skillMarketplace) {
        taskManager.deleteItem({ skillMarketplace: currentMarketplaceItem.skillMarketplace });
      }
    }
  } else if (sync.destination.skillPlugin) {
    let plugin = await db.skillPlugin.findFirst({
      where: { oid: sync.destination.skillPlugin.oid, status: 'active' },
      include: {
        skillConfiguration: true,
        skillPluginSkills: {
          where: {
            status: 'active',
            skill: {
              status: 'active'
            }
          },
          include: {
            skill: true,
            skillConfiguration: true
          }
        }
      }
    });

    if (plugin) {
      let skillPlugin = {
        ...plugin,
        skills: plugin.skillPluginSkills
      };

      let pluginHash = await getSerializerHash(applyPlugin, { skillPlugin });
      if (!pluginHash) return;
      let currentPluginItem = getCurrentPluginItem(skillPlugin.id);

      if (currentPluginItem?.hash === pluginHash) {
        taskManager.keepItem({ skillPlugin });
      } else {
        taskManager.addOrUpdateItem({ skillPlugin });
      }

      for (let skillPluginSkill of skillPlugin.skillPluginSkills) {
        let skillHash = await getSerializerHash(applySkill, {
          skill: skillPluginSkill.skill,
          skillPlugin,
          skillPluginSkill
        });
        if (!skillHash) return;
        let currentSkillItem = getCurrentSkillItem({
          skillId: skillPluginSkill.skill.id,
          skillPluginId: skillPlugin.id
        });

        if (currentSkillItem?.hash === skillHash) {
          taskManager.keepItem({
            skill: skillPluginSkill.skill,
            skillPlugin
          });
        } else {
          taskManager.addOrUpdateItem({
            skill: skillPluginSkill.skill,
            skillPlugin
          });
        }
      }
    }
  }

  let tasks = taskManager.getTasks();

  // Even with no item updates the sync continues to the reconcile stage, since
  // files left behind by items that no longer exist still have to be removed.
  // Reconcile cancels the sync when it finds nothing to do either.

  let names = await getSyncTaskNames(tasks);
  let prMetadata = getSyncPrMetadata({
    destination: sync.destination!,
    tasks,
    names,
    existingItemKeys
  });

  await db.skillDestinationSync.update({
    where: { oid: sync.oid },
    data: prMetadata
  });

  if (tasks.length === 0) {
    await syncReconcileQueue.add({
      skillDestinationSyncId: data.skillDestinationSyncId,
      hasChanges: false,
      skillRepositoryId: data.skillRepositoryId
    });
    return;
  }

  await appendSkillDestinationSyncLog(
    data.skillDestinationSyncId,
    `Prepared ${tasks.length} content ${tasks.length === 1 ? 'update' : 'updates'}.`
  );

  await syncProcessQueue.add({
    skillDestinationSyncId: data.skillDestinationSyncId,
    tasks,
    hasChanges: false,
    skillRepositoryId: data.skillRepositoryId
  });
});
