name = "@metorial/origin"
group = "oss"

[[dependencies]]
identifier = "@metorial/code-bucket-service-generated"
env = [
  { endpoint = "rpc", key = "CODE_BUCKET_SERVICE_URL", value = "{{HOSTNAME}}:{{PORT}}" },
  { endpoint = "workspace", key = "CODE_BUCKET_EDITOR_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[[dependencies]]
identifier = "@metorial/object-storage"
env = [
  { endpoint = "rpc", key = "OBJECT_STORAGE_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[test.e2e]
start = ["bun ./src/server.ts"]

[dev]
run = ["bun --watch ./src/server.ts"]

[endpoints.api]
port = 52090
env = [{ key = "ORIGIN_API_PORT", value = "{{PORT}}" }]

[endpoints.scm]
port = 52093
env = [
  { key = "ORIGIN_SCM_PORT", value = "{{PORT}}" },
  { key = "ORIGIN_SERVICE_PUBLIC_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
CODE_BUCKET_OBJECT_STORAGE_BUCKET = "code-bucket"
SCM_GITHUB_APP_ID = true
SCM_GITHUB_APP_SLUG = true
SCM_GITHUB_APP_PRIVATE_KEY_BASE_64 = true
SCM_GITHUB_APP_CLIENT_ID = true
SCM_GITHUB_APP_CLIENT_SECRET = true
SCM_GITLAB_CLIENT_ID = true
SCM_GITLAB_CLIENT_SECRET = true
SCM_BITBUCKET_CLIENT_ID = true
SCM_BITBUCKET_CLIENT_SECRET = true

[dev.db.main]
name = "origin"
engine = "postgres"
env = "DATABASE_URL"
