name = "@metorial/slates"
group = "oss"

[[dependencies]]
identifier = "@metorial/object-storage"
env = [
  { endpoint = "rpc", key = "OBJECT_STORAGE_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[[dependencies]]
identifier = "@metorial/function-bay"
env = [
  { endpoint = "api", key = "FUNCTION_BAY_API_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-function-bay" },
]

[[dependencies]]
identifier = "@metorial/signal"
env = [
  { endpoint = "api", key = "SIGNAL_API_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-signal" },
]

[[dependencies]]
identifier = "@metorial/nebula"
env = [
  { endpoint = "api", key = "NEBULA_API_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-nebula" },
]

[test.e2e]
start = ["bun ./src/server.ts"]

[dev]
prepare = ["admin:build"]
run = ["bun --watch ./src/server.ts"]

[endpoints.public]
port = 52045
env = [
  { key = "SLATES_HUB_PUBLIC_PORT", value = "{{PORT}}" },
  { key = "SERVICE_PUBLIC_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[endpoints.internal]
port = 52046
env = [{ key = "SLATES_HUB_INTERNAL_PORT", value = "{{PORT}}" }]

[endpoints.admin]
port = 52047
env = [{ key = "SLATES_HUB_ADMIN_PORT", value = "{{PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
ENCRYPTION_KEY = "sTrG+z8ewVo7JJsgmv39UL/YDdgxlHSVhVPJOV7Omdg"
FUNCTION_BAY_TENANT_IDENTIFIER = "dev-tenant"
FUNCTION_BAY_DEFAULT_MEMORY_MB = "512"
FUNCTION_BAY_DEFAULT_TIMEOUT_SECONDS = "60"
SIGNAL_SENDER_IDENTIFIER = "dev-slates-hub"
INVOCATIONS_BUCKET_NAME = "dev-invocations"
SLATES_HUB_INSTANCE_IDENTIFIER = "dev-slates-hub"
SUPPORTS_PREBUILT_SLATES = "true"
NEBULA_CONSUMER_IDENTIFIER = "dev-slates-hub"
NEBULA_CONSUMER_TOKEN = "local-dev-nebula-slates-registration-secret"
SLATES_DELEGATE_SECRETS_TO_NEBULA = "true"

[dev.db.main]
name = "slates-hub"
engine = "postgres"
env = "DATABASE_URL"
