name = "@metorial/ares"
group = "oss"

[[dependencies]]
identifier = "@metorial/relay"
env = [
  { endpoint = "rpc", key = "RELAY_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-relay" },
]

[test.e2e]
start = ["test:start-e2e"]

[dev]
prepare = ["frontend:build"]
run = ["dev:start"]

[endpoints.auth]
port = 52120
env = [
  { key = "ARES_AUTH_PORT", value = "{{PORT}}" },
  { key = "ARES_AUTH_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[endpoints.admin]
port = 52121
env = [
  { key = "ARES_ADMIN_PORT", value = "{{PORT}}" },
  { key = "ARES_ADMIN_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[endpoints.sso]
port = 52122
env = [
  { key = "ARES_SSO_PORT", value = "{{PORT}}" },
  { key = "ARES_SSO_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[endpoints.internal]
port = 52123
env = [{ key = "ARES_INTERNAL_PORT", value = "{{PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
EMAIL_NAME = "Ares Dev"
EMAIL_ADDRESS = "dev@metorial.com"
SAML_AUDIENCE = "https://saml.dev.metorial.com"
AUTH_TICKET_SECRET = "dev-secret-change-in-production"
TURNSTILE_SITE_KEY = true
TURNSTILE_SECRET_KEY = true

[dev.db.main]
package = "@metorial/ares"
name = "ares"
engine = "postgres"
env = "DATABASE_URL"

[dev.db.sso]
package = "@metorial/ares"
name = "ares-sso"
engine = "postgres"
env = "SSO_DATABASE_URL"
