use std::{fs, path::PathBuf};

use miette::{IntoDiagnostic, Result, WrapErr};

use crate::{
    manifest,
    root::{ProjectRoot, RootKind},
};

const WORKFLOW_PATH: &str = ".github/workflows/control-tests.yml";

pub fn generate(project: &ProjectRoot) -> Result<PathBuf> {
    let manifests = manifest::discover(&project.oss)?;
    let mut services = manifests
        .iter()
        .filter(|loaded| loaded.manifest.mode.applies_to(&RootKind::Standalone))
        .filter(|loaded| loaded.manifest.test.e2e.is_some())
        .filter_map(|loaded| {
            loaded
                .manifest
                .package
                .as_ref()
                .map(|package| package.name.clone())
        })
        .collect::<Vec<_>>();
    services.sort();
    services.dedup();

    let path = project.oss.join(WORKFLOW_PATH);
    let contents = render(&services);
    if fs::read_to_string(&path).ok().as_deref() == Some(&contents) {
        return Ok(path);
    }
    fs::create_dir_all(path.parent().expect("workflow path has a parent"))
        .into_diagnostic()
        .wrap_err("could not create the GitHub Actions workflow directory")?;
    fs::write(&path, contents)
        .into_diagnostic()
        .wrap_err_with(|| format!("could not write {}", path.display()))?;
    Ok(path)
}

fn render(services: &[String]) -> String {
    let matrix = services
        .iter()
        .map(|service| {
            format!(
                "          - {}\n",
                serde_json::to_string(service).expect("service names are strings")
            )
        })
        .collect::<String>();

    format!(
        "# This file is generated by `control generate actions`. Do not edit it directly.\n\
         name: Control Tests\n\
         \n\
         on:\n\
         \x20 workflow_dispatch:\n\
         \x20 pull_request:\n\
         \x20 push:\n\
         \n\
         permissions:\n\
         \x20 contents: read\n\
         \n\
         jobs:\n\
         \x20 unit:\n\
         \x20   name: Unit tests\n\
         \x20   runs-on: ubuntu-latest\n\
         \x20   steps:\n\
         \x20     - name: Checkout repository\n\
         \x20       uses: actions/checkout@v4\n\
         \x20       with:\n\
         \x20         submodules: recursive\n\
         \x20         token: ${{{{ secrets.GH_TOKEN }}}}\n\
         \x20     - name: Install Rust\n\
         \x20       uses: dtolnay/rust-toolchain@stable\n\
         \x20       with:\n\
         \x20         toolchain: 1.91.1\n\
         \x20     - name: Run unit tests\n\
         \x20       run: cargo run --quiet --manifest-path src/control/Cargo.toml -- test unit --all\n\
         \n\
         \x20 e2e:\n\
         \x20   name: E2E (${{{{ matrix.service }}}})\n\
         \x20   runs-on: ubuntu-latest\n\
         \x20   strategy:\n\
         \x20     fail-fast: false\n\
         \x20     matrix:\n\
         \x20       service:\n\
         {matrix}\
         \x20   steps:\n\
         \x20     - name: Checkout repository\n\
         \x20       uses: actions/checkout@v4\n\
         \x20       with:\n\
         \x20         submodules: recursive\n\
         \x20         token: ${{{{ secrets.GH_TOKEN }}}}\n\
         \x20     - name: Install Rust\n\
         \x20       uses: dtolnay/rust-toolchain@stable\n\
         \x20       with:\n\
         \x20         toolchain: 1.91.1\n\
         \x20     - name: Run E2E tests\n\
         \x20       run: cargo run --quiet --manifest-path src/control/Cargo.toml -- test e2e \"${{{{ matrix.service }}}}\"\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_unit_and_parallel_e2e_jobs() {
        let workflow = render(&["@metorial/api".into(), "@metorial/forge".into()]);
        assert!(workflow.contains("test unit --all"));
        assert!(workflow.contains("fail-fast: false"));
        assert!(workflow.contains("- \"@metorial/api\""));
        assert!(workflow.contains("- \"@metorial/forge\""));
        assert!(workflow.contains("test e2e \"${{ matrix.service }}\""));
        assert!(workflow.starts_with("# This file is generated"));
    }
}
