name = "@metorial/slates-registry"
group = "oss"

[dev]
prepare = ["admin:build"]
run = ["bun --watch ./src/server.ts"]

[[dev.expose]]
port = 52040

[[dev.expose]]
port = 52041

[[dev.expose]]
port = 52042

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
REDIS_URL = "redis://localhost:{{CONTROL_PORT_REDIS}}/0"
OBJECT_STORAGE_URL = "http://services:52010"
PACKAGE_BUCKET_NAME = "package-bucket"
NPM_REGISTRY_URL = "https://registry.npmjs.org"
NPM_SEARCH_URL = "https://registry.npmjs.org/-/v1/search"
NPM_TOKEN = true
SERVICE_PUBLIC_URL = "http://{{HOSTNAME}}:52040"
NPM_ORG = "slates-integrations"

[dev.db.main]
name = "slates-registry"
engine = "postgres"
env = "DATABASE_URL"
