name = "@metorial/slates-registry"
group = "oss"

[[dependencies]]
identifier = "@metorial/object-storage"
env = [
  { endpoint = "rpc", key = "OBJECT_STORAGE_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[test.e2e]
prepare = []
start = ["test:start-e2e"]

[dev]
prepare = ["admin:build"]
run = ["dev:start"]

[endpoints.public]
port = 52040
env = [
  { key = "SLATES_REGISTRY_PUBLIC_PORT", value = "{{BIND_PORT}}" },
  { key = "SERVICE_PUBLIC_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[endpoints.internal]
port = 52041
env = [{ key = "SLATES_REGISTRY_INTERNAL_PORT", value = "{{BIND_PORT}}" }]

[endpoints.admin]
port = 52042
env = [{ key = "SLATES_REGISTRY_ADMIN_PORT", value = "{{BIND_PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
PACKAGE_BUCKET_NAME = "package-bucket"
NPM_REGISTRY_URL = "https://registry.npmjs.org"
NPM_SEARCH_URL = "https://registry.npmjs.org/-/v1/search"
NPM_TOKEN = true
NPM_ORG = "slates-integrations"

[dev.db.main]
package = "@metorial/slates-registry"
name = "slates-registry"
engine = "postgres"
env = "DATABASE_URL"
