import { createQueue } from '@lowerdeck/queue';
import { db, env } from '@metorial-cargo/db';
import { createTaskManager, type SyncTask } from './_lib/task';
import { syncFinishQueue } from './finish';
import { syncProcessQueue } from './process';

export let syncCollectQueue = createQueue<{
  skillDestinationSyncId: string;
}>({
  redisUrl: env.service.REDIS_URL,
  name: 'cargo/skill/sync/collect',
  workerOpts: {
    concurrency: 10
  }
});

let getSyncTaskLabel = (
  task: SyncTask,
  names: {
    marketplaces: Map<string, string>;
    plugins: Map<string, string>;
    skills: Map<string, string>;
  }
) => {
  let action = task.action === 'delete' ? 'Remove' : 'Update';

  if (task.type === 'marketplace') {
    return `${action} marketplace ${names.marketplaces.get(task.skillMarketplaceId) ?? task.skillMarketplaceId}`;
  }

  if (task.type === 'plugin') {
    return `${action} plugin ${names.plugins.get(task.skillPluginId) ?? task.skillPluginId}`;
  }

  return `${action} skill ${names.skills.get(task.skillId) ?? task.skillId} in plugin ${
    names.plugins.get(task.skillPluginId) ?? task.skillPluginId
  }`;
};

let getSyncPrMetadata = (d: {
  destination: {
    skillMarketplace?: { name: string; id: string } | null;
    skillPlugin?: { name: string; id: string } | null;
  };
  tasks: SyncTask[];
  names: {
    marketplaces: Map<string, string>;
    plugins: Map<string, string>;
    skills: Map<string, string>;
  };
}) => {
  let target = d.destination.skillMarketplace
    ? `marketplace ${d.destination.skillMarketplace.name}`
    : d.destination.skillPlugin
      ? `plugin ${d.destination.skillPlugin.name}`
      : 'skill destination';

  let title = `Update ${target}`;
  let taskLines = d.tasks.map(task => `- ${getSyncTaskLabel(task, d.names)}`);

  return {
    prName: title,
    prDescription: [
      `Hello 👋! I'm the **Metorial Assistant** updating the contents for the Metorial ${target}.`,
      '',
      ...taskLines,
      '',
      `<sub>This PR was automatically generated by the Metorial Assistant.</sub>`
    ].join('\n'),
    commitMessage: title
  };
};

let getSyncTaskNames = async (tasks: SyncTask[]) => {
  let marketplaceIds = tasks.flatMap(task =>
    task.type === 'marketplace' ? [task.skillMarketplaceId] : []
  );
  let pluginIds = tasks.flatMap(task =>
    task.type === 'plugin' || task.type === 'skill' ? [task.skillPluginId] : []
  );
  let skillIds = tasks.flatMap(task => (task.type === 'skill' ? [task.skillId] : []));

  let [marketplaces, plugins, skills] = await Promise.all([
    marketplaceIds.length
      ? db.skillMarketplace.findMany({
          where: { id: { in: [...new Set(marketplaceIds)] } },
          select: { id: true, name: true }
        })
      : [],
    pluginIds.length
      ? db.skillPlugin.findMany({
          where: { id: { in: [...new Set(pluginIds)] } },
          select: { id: true, name: true }
        })
      : [],
    skillIds.length
      ? db.skill.findMany({
          where: { id: { in: [...new Set(skillIds)] } },
          select: { id: true, name: true }
        })
      : []
  ]);

  return {
    marketplaces: new Map(marketplaces.map(marketplace => [marketplace.id, marketplace.name])),
    plugins: new Map(plugins.map(plugin => [plugin.id, plugin.name])),
    skills: new Map(skills.map(skill => [skill.id, skill.name ?? 'Untitled skill']))
  };
};

export let syncCollectQueueProcessor = syncCollectQueue.process(async data => {
  let sync = await db.skillDestinationSync.findUnique({
    where: { id: data.skillDestinationSyncId },
    include: {
      destination: {
        include: {
          skillMarketplace: true,
          skillPlugin: true
        }
      }
    }
  });
  if (!sync || sync.status !== 'processing') return;

  let currentItems = await db.skillDestinationItem.findMany({
    where: { destinationOid: sync.destination.oid },
    include: { skill: true, skillPlugin: true, skillMarketplace: true }
  });

  let taskManager = createTaskManager(currentItems);

  if (sync.destination.skillMarketplace) {
    let marketplace = await db.skillMarketplace.findFirst({
      where: { oid: sync.destination.skillMarketplace.oid, status: 'active' },
      include: {
        plugins: {
          where: {
            status: 'active',
            skillPlugin: {
              status: 'active'
            }
          },
          include: {
            skillPlugin: {
              include: {
                skillPluginSkills: {
                  where: {
                    status: 'active',
                    skill: {
                      status: 'active'
                    }
                  },
                  include: {
                    skill: true
                  }
                }
              }
            }
          }
        }
      }
    });

    if (marketplace) {
      taskManager.addOrUpdateItem({ skillMarketplace: marketplace });

      for (let plugin of marketplace.plugins) {
        taskManager.addOrUpdateItem({ skillPlugin: plugin.skillPlugin });

        for (let skillPluginSkill of plugin.skillPlugin.skillPluginSkills) {
          taskManager.addOrUpdateItem({
            skill: skillPluginSkill.skill,
            skillPlugin: plugin.skillPlugin
          });
        }
      }
    } else {
      let currentMarketplaceItem = currentItems.find(
        item => item.skillMarketplace?.id === sync.destination.skillMarketplace?.id
      );

      if (currentMarketplaceItem?.skillMarketplace) {
        taskManager.deleteItem({ skillMarketplace: currentMarketplaceItem.skillMarketplace });
      }
    }
  } else if (sync.destination.skillPlugin) {
    let plugin = await db.skillPlugin.findFirst({
      where: { oid: sync.destination.skillPlugin.oid, status: 'active' },
      include: {
        skillPluginSkills: {
          where: {
            status: 'active',
            skill: {
              status: 'active'
            }
          },
          include: {
            skill: true
          }
        }
      }
    });

    if (plugin) {
      taskManager.addOrUpdateItem({ skillPlugin: plugin });

      for (let skillPluginSkill of plugin.skillPluginSkills) {
        taskManager.addOrUpdateItem({
          skill: skillPluginSkill.skill,
          skillPlugin: plugin
        });
      }
    }
  }

  let tasks = taskManager.getTasks();
  let names = await getSyncTaskNames(tasks);
  let prMetadata = getSyncPrMetadata({
    destination: sync.destination,
    tasks,
    names
  });

  await db.skillDestinationSync.update({
    where: { oid: sync.oid },
    data: prMetadata
  });

  if (tasks.length === 0) {
    await syncFinishQueue.add({
      skillDestinationSyncId: data.skillDestinationSyncId
    });
    return;
  }

  await syncProcessQueue.add({
    skillDestinationSyncId: data.skillDestinationSyncId,
    tasks
  });
});
