import { createQueue } from '@lowerdeck/queue';
import { db, env } from '@metorial-cargo/db';
import { applyMarketplace } from '../../serializers/marketplace';
import { applyPlugin } from '../../serializers/plugin';
import { applySkill } from '../../serializers/skill';
import { appendSkillDestinationSyncLog } from './_lib/logs';
import { createTaskManager, type SyncTask } from './_lib/task';
import { syncFinishQueue } from './finish';
import { syncProcessQueue } from './process';

export let syncCollectQueue = createQueue<{
  skillDestinationSyncId: string;
}>({
  redisUrl: env.service.REDIS_URL,
  name: 'cargo/skill/sync/collect',
  workerOpts: {
    concurrency: 10
  }
});

let getSyncTaskLabel = (
  task: SyncTask,
  names: {
    marketplaces: Map<string, string>;
    plugins: Map<string, string>;
    skills: Map<string, string>;
  },
  existingItemKeys: Set<string>
) => {
  let itemKey = getSyncTaskItemKey(task);
  let action =
    task.action === 'delete' ? 'Remove' : existingItemKeys.has(itemKey) ? 'Update' : 'Add';

  if (task.type === 'marketplace') {
    return `${action} marketplace ${names.marketplaces.get(task.skillMarketplaceId) ?? task.skillMarketplaceId}`;
  }

  if (task.type === 'plugin') {
    return `${action} plugin ${names.plugins.get(task.skillPluginId) ?? task.skillPluginId}`;
  }

  return `${action} skill ${names.skills.get(task.skillId) ?? task.skillId} in plugin ${
    names.plugins.get(task.skillPluginId) ?? task.skillPluginId
  }`;
};

let getSyncTaskItemKey = (task: SyncTask) => {
  if (task.type === 'skill') return `skill:${task.skillId}:${task.skillPluginId}`;
  if (task.type === 'plugin') return `plugin:${task.skillPluginId}`;
  return `marketplace:${task.skillMarketplaceId}`;
};

let getSyncTaskItemKeyFromItem = (item: {
  skill?: { id: string } | null;
  skillPlugin?: { id: string } | null;
  skillMarketplace?: { id: string } | null;
}) => {
  if (item.skill) {
    if (!item.skillPlugin) throw new Error('Skill item must have skillPlugin');
    return `skill:${item.skill.id}:${item.skillPlugin.id}`;
  }

  if (item.skillPlugin) return `plugin:${item.skillPlugin.id}`;
  if (item.skillMarketplace) return `marketplace:${item.skillMarketplace.id}`;
  throw new Error('Invalid item');
};

let getSyncPrMetadata = (d: {
  destination: {
    skillMarketplace?: { name: string; id: string } | null;
    skillPlugin?: { name: string; id: string } | null;
  };
  tasks: SyncTask[];
  names: {
    marketplaces: Map<string, string>;
    plugins: Map<string, string>;
    skills: Map<string, string>;
  };
  existingItemKeys: Set<string>;
}) => {
  let target = d.destination.skillMarketplace
    ? `marketplace ${d.destination.skillMarketplace.name}`
    : d.destination.skillPlugin
      ? `plugin ${d.destination.skillPlugin.name}`
      : 'skill destination';

  let title = `Update ${target}`;
  let taskLines = d.tasks.map(
    task => `- ${getSyncTaskLabel(task, d.names, d.existingItemKeys)}`
  );

  return {
    prName: title,
    prDescription: [
      'Hey 👋',
      '',
      `I'm the **Metorial Assistant** updating the contents for the ${target}.`,
      '',
      ...taskLines,
      '',
      `<sub>This PR was automatically generated by the Metorial Assistant.</sub>`
    ].join('\n'),
    commitMessage: title
  };
};

let getSyncTaskNames = async (tasks: SyncTask[]) => {
  let marketplaceIds = tasks.flatMap(task =>
    task.type === 'marketplace' ? [task.skillMarketplaceId] : []
  );
  let pluginIds = tasks.flatMap(task =>
    task.type === 'plugin' || task.type === 'skill' ? [task.skillPluginId] : []
  );
  let skillIds = tasks.flatMap(task => (task.type === 'skill' ? [task.skillId] : []));

  let [marketplaces, plugins, skills] = await Promise.all([
    marketplaceIds.length
      ? db.skillMarketplace.findMany({
          where: { id: { in: [...new Set(marketplaceIds)] } },
          select: { id: true, name: true }
        })
      : [],
    pluginIds.length
      ? db.skillPlugin.findMany({
          where: { id: { in: [...new Set(pluginIds)] } },
          select: { id: true, name: true }
        })
      : [],
    skillIds.length
      ? db.skill.findMany({
          where: { id: { in: [...new Set(skillIds)] } },
          select: { id: true, name: true }
        })
      : []
  ]);

  return {
    marketplaces: new Map(marketplaces.map(marketplace => [marketplace.id, marketplace.name])),
    plugins: new Map(plugins.map(plugin => [plugin.id, plugin.name])),
    skills: new Map(skills.map(skill => [skill.id, skill.name ?? 'Untitled skill']))
  };
};

export let syncCollectQueueProcessor = syncCollectQueue.process(async data => {
  let sync = await db.skillDestinationSync.findUnique({
    where: { id: data.skillDestinationSyncId },
    include: {
      destination: {
        include: {
          skillMarketplace: true,
          skillPlugin: true
        }
      }
    }
  });
  if (!sync || sync.status !== 'processing') return;

  await appendSkillDestinationSyncLog(
    data.skillDestinationSyncId,
    'Preparing content updates.'
  );

  let currentItems = await db.skillDestinationItem.findMany({
    where: { destinationOid: sync.destination.oid },
    include: { skill: true, skillPlugin: true, skillMarketplace: true }
  });

  let taskManager = createTaskManager(currentItems);
  let existingItemKeys = new Set(currentItems.map(item => getSyncTaskItemKeyFromItem(item)));

  let getSerializerHash = async <Input, InitResult>(
    serializer: {
      init: (input: Input) => Promise<InitResult>;
      getHash: (input: Input, initResult: InitResult) => Promise<string>;
    },
    input: Input
  ) => {
    let initResult = await serializer.init(input);
    return await serializer.getHash(input, initResult);
  };

  let getCurrentMarketplaceItem = (marketplaceId: string) =>
    currentItems.find(item => item.skillMarketplace?.id === marketplaceId);

  let getCurrentPluginItem = (pluginId: string) =>
    currentItems.find(item => !item.skill && item.skillPlugin?.id === pluginId);

  let getCurrentSkillItem = (d: { skillId: string; skillPluginId: string }) =>
    currentItems.find(
      item => item.skill?.id === d.skillId && item.skillPlugin?.id === d.skillPluginId
    );

  if (sync.destination.skillMarketplace) {
    let marketplace = await db.skillMarketplace.findFirst({
      where: { oid: sync.destination.skillMarketplace.oid, status: 'active' },
      include: {
        skillConfiguration: true,
        plugins: {
          where: {
            status: 'active',
            skillPlugin: {
              status: 'active'
            }
          },
          include: {
            skillConfiguration: true,
            skillPlugin: {
              include: {
                skillConfiguration: true,
                skillPluginSkills: {
                  where: {
                    status: 'active',
                    skill: {
                      status: 'active'
                    }
                  },
                  include: {
                    skill: true,
                    skillConfiguration: true
                  }
                }
              }
            }
          }
        }
      }
    });

    if (marketplace) {
      let marketplaceHash = await getSerializerHash(applyMarketplace, {
        skillMarketplace: marketplace
      });
      let currentMarketplaceItem = getCurrentMarketplaceItem(marketplace.id);

      if (currentMarketplaceItem?.hash === marketplaceHash) {
        taskManager.keepItem({ skillMarketplace: marketplace });
      } else {
        taskManager.addOrUpdateItem({ skillMarketplace: marketplace });
      }

      for (let marketplacePlugin of marketplace.plugins) {
        let skillPlugin = {
          ...marketplacePlugin.skillPlugin,
          skills: marketplacePlugin.skillPlugin.skillPluginSkills
        };
        let skillMarketplacePlugin = {
          ...marketplacePlugin,
          plugin: skillPlugin
        };

        let pluginHash = await getSerializerHash(applyPlugin, {
          skillPlugin,
          skillMarketplace: marketplace,
          skillMarketplacePlugin
        });
        let currentPluginItem = getCurrentPluginItem(skillPlugin.id);

        if (currentPluginItem?.hash === pluginHash) {
          taskManager.keepItem({ skillPlugin });
        } else {
          taskManager.addOrUpdateItem({ skillPlugin });
        }

        for (let skillPluginSkill of skillPlugin.skillPluginSkills) {
          let skillHash = await getSerializerHash(applySkill, {
            skill: skillPluginSkill.skill,
            skillPlugin,
            skillPluginSkill,
            skillMarketplace: marketplace,
            skillMarketplacePlugin
          });
          let currentSkillItem = getCurrentSkillItem({
            skillId: skillPluginSkill.skill.id,
            skillPluginId: skillPlugin.id
          });

          if (currentSkillItem?.hash === skillHash) {
            taskManager.keepItem({
              skill: skillPluginSkill.skill,
              skillPlugin
            });
          } else {
            taskManager.addOrUpdateItem({
              skill: skillPluginSkill.skill,
              skillPlugin
            });
          }
        }
      }
    } else {
      let currentMarketplaceItem = currentItems.find(
        item => item.skillMarketplace?.id === sync.destination.skillMarketplace?.id
      );

      if (currentMarketplaceItem?.skillMarketplace) {
        taskManager.deleteItem({ skillMarketplace: currentMarketplaceItem.skillMarketplace });
      }
    }
  } else if (sync.destination.skillPlugin) {
    let plugin = await db.skillPlugin.findFirst({
      where: { oid: sync.destination.skillPlugin.oid, status: 'active' },
      include: {
        skillConfiguration: true,
        skillPluginSkills: {
          where: {
            status: 'active',
            skill: {
              status: 'active'
            }
          },
          include: {
            skill: true,
            skillConfiguration: true
          }
        }
      }
    });

    if (plugin) {
      let skillPlugin = {
        ...plugin,
        skills: plugin.skillPluginSkills
      };

      let pluginHash = await getSerializerHash(applyPlugin, { skillPlugin });
      let currentPluginItem = getCurrentPluginItem(skillPlugin.id);

      if (currentPluginItem?.hash === pluginHash) {
        taskManager.keepItem({ skillPlugin });
      } else {
        taskManager.addOrUpdateItem({ skillPlugin });
      }

      for (let skillPluginSkill of skillPlugin.skillPluginSkills) {
        let skillHash = await getSerializerHash(applySkill, {
          skill: skillPluginSkill.skill,
          skillPlugin,
          skillPluginSkill
        });
        let currentSkillItem = getCurrentSkillItem({
          skillId: skillPluginSkill.skill.id,
          skillPluginId: skillPlugin.id
        });

        if (currentSkillItem?.hash === skillHash) {
          taskManager.keepItem({
            skill: skillPluginSkill.skill,
            skillPlugin
          });
        } else {
          taskManager.addOrUpdateItem({
            skill: skillPluginSkill.skill,
            skillPlugin
          });
        }
      }
    }
  }

  let tasks = taskManager.getTasks();
  let names = await getSyncTaskNames(tasks);
  let prMetadata = getSyncPrMetadata({
    destination: sync.destination,
    tasks,
    names,
    existingItemKeys
  });

  await db.skillDestinationSync.update({
    where: { oid: sync.oid },
    data: prMetadata
  });

  if (tasks.length === 0) {
    await appendSkillDestinationSyncLog(
      data.skillDestinationSyncId,
      'No content updates were needed.'
    );
    await syncFinishQueue.add({
      skillDestinationSyncId: data.skillDestinationSyncId
    });
    return;
  }

  await appendSkillDestinationSyncLog(
    data.skillDestinationSyncId,
    `Prepared ${tasks.length} content ${tasks.length === 1 ? 'update' : 'updates'}.`
  );

  await syncProcessQueue.add({
    skillDestinationSyncId: data.skillDestinationSyncId,
    tasks
  });
});
