name = "@metorial-subspace/app-worker"
group = "oss"

[[dependencies]]
identifier = "@metorial/object-storage"
env = [
  { endpoint = "rpc", key = "OBJECT_STORAGE_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[[dependencies]]
identifier = "@metorial-subspace/app-controller"

[[dependencies]]
identifier = "@metorial-subspace/app-public"
env = [
  { endpoint = "public", key = "PUBLIC_SERVICE_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[[dependencies]]
identifier = "@metorial/shuttle"
env = [
  { endpoint = "api", key = "SHUTTLE_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-shuttle" },
  { endpoint = "api", key = "SHUTTLE_LIVE_URL", value = "ws://{{HOSTNAME}}:{{PORT}}" },
  { endpoint = "public", key = "SHUTTLE_PUBLIC_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[[dependencies]]
identifier = "@metorial/slates"
env = [
  { endpoint = "internal", key = "SLATES_HUB_URL", value = "http://{{HOSTNAME}}:{{PORT}}/slates-hub" },
  { endpoint = "public", key = "SLATES_HUB_PUBLIC_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[[dependencies]]
identifier = "@metorial/voyager"
env = [
  { endpoint = "rpc", key = "VOYAGER_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-voyager" },
]

[[dependencies]]
identifier = "@metorial/origin"
env = [
  { endpoint = "api", key = "ORIGIN_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-origin" },
]

[[dependencies]]
identifier = "@metorial/signal"
env = [
  { endpoint = "api", key = "SIGNAL_API_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-signal" },
]

[[dependencies]]
identifier = "@metorial/function-bay"
env = [
  { endpoint = "api", key = "FUNCTION_BAY_API_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-function-bay" },
]

[[dependencies]]
identifier = "@metorial-cargo/service"
env = [
  { endpoint = "api", key = "CARGO_API_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-cargo" },
]

[test.e2e]
start = ["test:start-e2e"]

[dev]
run = ["dev:start"]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[[resources]]
type = "nats"
env = [{ key = "NATS_URL", value = "nats://{{HOSTNAME}}:{{PORT}}" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
MESSAGE_BUCKET_NAME = "messages"
PROVIDER_TELEMETRY_ERROR_GROUPS_BUCKET_NAME = "provider-telemetry-error-groups"
REGISTRY_URL = "https://metorial-saas-dev2.registry.metorial-enterprise.com/metorial-registry-root"
SCOUT_URL = "https://scout-fra-fly-prod.metorial-enterprise.com/metorial-scout"
SCOUT_TOKEN = true

[dev.db.main]
package = "@metorial-subspace/db"
name = "subspace"
engine = "postgres"
env = "DATABASE_URL"
