name = "@metorial-subspace/app-worker"
group = "oss"
dependencies = [
  "@metorial/object-storage",
  "@metorial-subspace/app-controller",
  "@metorial/shuttle",
  "@metorial/slates",
  "@metorial/voyager",
  "@metorial/origin",
  "@metorial/signal",
  "@metorial/function-bay",
]

[test.e2e]
start = ["bun ./src/server.ts"]

[dev]
run = ["bun --watch ./src/server.ts"]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
REDIS_URL = "redis://localhost:{{CONTROL_PORT_REDIS}}/0"
NATS_URL = "nats://localhost:34222"
PUBLIC_SERVICE_URL = "http://{{HOSTNAME}}:52071"
SHUTTLE_URL = "http://localhost:52080/metorial-shuttle"
SHUTTLE_LIVE_URL = "ws://localhost:52080"
SHUTTLE_PUBLIC_URL = "http://{{HOSTNAME}}:52081"
SLATES_HUB_URL = "http://localhost:52046/slates-hub"
SLATES_HUB_PUBLIC_URL = "http://{{HOSTNAME}}:52045"
VOYAGER_URL = "http://localhost:52060/metorial-voyager"
OBJECT_STORAGE_URL = "http://services:52010"
MESSAGE_BUCKET_NAME = "messages"
PROVIDER_TELEMETRY_ERROR_GROUPS_BUCKET_NAME = "provider-telemetry-error-groups"
ORIGIN_URL = "http://localhost:52090/metorial-origin"
REGISTRY_URL = "https://metorial-saas-dev2.registry.metorial-enterprise.com/metorial-registry-root"
SCOUT_URL = "https://scout-fra-fly-prod.metorial-enterprise.com/metorial-scout"
SCOUT_TOKEN = true
SIGNAL_API_URL = "http://localhost:52050/metorial-signal"
CARGO_API_URL = "http://localhost:52150/metorial-cargo"
FUNCTION_BAY_API_URL = "http://localhost:52030/metorial-function-bay"

[dev.db.main]
name = "subspace"
engine = "postgres"
env = "DATABASE_URL"
