name = "@metorial-subspace/app-public"
group = "oss"
mode = "oss"

[dev]
prepare = ["frontend:build"]
run = ["bun --watch ./src/server.ts"]

[[dev.expose]]
port = 52071

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
INTEGRATIONS_API_URL = "http://{{HOSTNAME}}:4316"
INTEGRATIONS_UI_URL = "http://{{HOSTNAME}}:52071"
