name = "@metorial/synthesis"
group = "oss"

[[dependencies]]
identifier = "@metorial-subspace/app-controller"
env = [
  { endpoint = "api", key = "SUBSPACE_URL", value = "http://{{HOSTNAME}}:{{PORT}}/subspace-controller" },
  { endpoint = "connection", key = "SUBSPACE_CONNECTION_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[test.e2e]
start = ["test:start-e2e"]

[dev]
run = ["dev:start"]

[endpoints.api]
port = 52160
env = [{ key = "SYNTHESIS_API_PORT", value = "{{BIND_PORT}}" }]

[endpoints.health]
port = 52161
env = [{ key = "SYNTHESIS_HEALTH_PORT", value = "{{BIND_PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
AI_GATEWAY_API_KEY = true
SCOUT_URL = "https://scout-fra-fly-prod.metorial-enterprise.com/metorial-scout"
SCOUT_TOKEN = true
SUBSPACE_SOLUTION = "metorial-dev"

[dev.db.main]
package = "@metorial/synthesis"
name = "synthesis"
engine = "postgres"
env = "SYNTHESIS_DATABASE_URL"
