name = "@metorial/relay"
group = "oss"

[test.e2e]
start = ["test:start-e2e"]

[dev]
run = ["dev:start"]

[endpoints.rpc]
port = 52110
env = [{ key = "RELAY_PORT", value = "{{PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"

[dev.db.main]
package = "@metorial/relay"
name = "relay"
engine = "postgres"
env = "DATABASE_URL"
