name = "@metorial/db"
group = "oss"

[[dependencies]]
identifier = "@metorial/object-storage"

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"

[dev.db.main]
package = "@metorial/db"
name = "metorial-enterprise"
engine = "postgres"
env = "DATABASE_URL"
