name = "@metorial/object-storage"
group = "oss"

[test.e2e]
start = ["test:start-e2e"]

[dev]
run = ["dev:start"]

[endpoints.rpc]
port = 52010
env = [{ key = "OBJECT_STORE__SERVER__PORT", value = "{{BIND_PORT}}" }]

[dev.env]
OBJECT_STORE__SERVER__HOST = "0.0.0.0"
OBJECT_STORE__BACKEND__TYPE = "local"
OBJECT_STORE__BACKEND__ROOT_PATH = "/tmp/metorial-object-storage"
OBJECT_STORE__BACKEND__PHYSICAL_BUCKET = "metorial-local"
RUST_LOG = "object_store=info,tower_http=info"
