import type { BuildBuilder } from './base';
import {
  assertArtifactsConfigured,
  assertHasMainInputs,
  assertRuntimeCommand,
  buildCommandForPlan,
  createBasePlan,
  defaultRuntime,
  formatContainerWorkdir,
  formatRunStep,
  renderApkInstall,
  renderArtifactLines,
  renderCopyLines,
  shouldUseDockerCacheMounts
} from './base';
import type { GeneratedBuildPlan } from '../types';

let defaultGoRuntime = defaultRuntime(undefined, {
  base_image: 'gcr.io/distroless/base-debian12',
  packages: [],
  env: {},
  expose: [],
  command: '',
  healthcheck: '',
  user: '',
  workdir: '/app'
});

let pinBuilderImage = (image: string): string => {
  if (image === 'oven/bun:1.2') return 'oven/bun:1.2.22';
  if (image === 'oven/bun:1.2-alpine') return 'oven/bun:1.2.22-alpine';
  return image;
};

let renderGoDockerfile = (plan: GeneratedBuildPlan): string => {
  let builderImage = pinBuilderImage(
    plan.service.config.build?.builder_image?.image ?? 'golang:1.24-alpine'
  );
  let systemPackages = plan.service.config.build?.install?.system_packages ?? ['git', 'ca-certificates'];
  let manifestLines = renderCopyLines(plan.manifestFiles);
  let inputLines = renderCopyLines(plan.inputPaths);
  let installLayerLines = plan.installLayers.map(layer => {
    let cwd = formatContainerWorkdir(layer.cwdRelativeToContext ?? '.');
    let cacheMount = shouldUseDockerCacheMounts()
      ? layer.tool === 'bun'
        ? '--mount=type=cache,id=control-bun-install,target=/root/.bun/install/cache,sharing=locked '
        : layer.tool === 'go'
          ? '--mount=type=cache,id=control-go-mod,target=/go/pkg/mod,sharing=locked '
          : ''
      : '';
    return `RUN ${cacheMount}cd ${cwd} && ${formatRunStep(layer.command)}`;
  });
  let prebuildLines = plan.prebuildSteps.map(step => {
    let cwd = formatContainerWorkdir(step.cwdRelativeToContext ?? '.');
    return `RUN cd ${cwd} && ${formatRunStep(step.run)}`;
  });
  let artifactLines = renderArtifactLines(plan);
  let exposeLines = plan.runtime.expose.map(port => `EXPOSE ${port}`);
  let envLines = Object.entries(plan.runtime.env).map(([key, value]) => `ENV ${key}=${JSON.stringify(value)}`);
  let runtimePackageLines = renderApkInstall(plan.runtime.packages);
  let healthcheckLines = plan.runtime.healthcheck
    ? [
        'HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\',
        `  CMD ${plan.runtime.healthcheck}`
      ]
    : [];

  let lines = [
    '# syntax=docker/dockerfile:1.7',
    '# generated by control bootstrap',
    `FROM ${builderImage} AS deps`,
    'WORKDIR /app',
    'ENV GOTOOLCHAIN=auto',
    ...renderApkInstall(systemPackages),
    ...manifestLines,
    ...installLayerLines,
    shouldUseDockerCacheMounts()
      ? `RUN --mount=type=cache,id=control-go-mod,target=/go/pkg/mod,sharing=locked cd ${plan.workspaceRoot} && go mod download`
      : `RUN cd ${plan.workspaceRoot} && go mod download`,
    '',
    'FROM deps AS build',
    'WORKDIR /app',
    ...inputLines,
    ...prebuildLines,
    shouldUseDockerCacheMounts()
      ? `RUN --mount=type=cache,id=control-go-mod,target=/go/pkg/mod,sharing=locked --mount=type=cache,id=control-go-build,target=/root/.cache/go-build,sharing=locked cd ${plan.workspaceRoot} && ${buildCommandForPlan(plan)}`
      : `RUN cd ${plan.workspaceRoot} && ${buildCommandForPlan(plan)}`,
    '',
    'FROM build AS workspace',
    `WORKDIR ${plan.workspaceRoot}`,
    'CMD ["sleep", "infinity"]',
    '',
    `FROM ${plan.runtime.base_image} AS runner`,
    `WORKDIR ${plan.runtime.workdir}`,
    ...runtimePackageLines,
    ...artifactLines,
    ...envLines,
    ...exposeLines,
    ...healthcheckLines,
    ...(plan.runtime.user ? [`USER ${plan.runtime.user}`] : []),
    `CMD ${JSON.stringify([plan.runtime.command])}`
  ];

  return lines.filter(Boolean).join('\n') + '\n';
};

export let goBuildBuilder: BuildBuilder = {
  kind: 'go',
  plan: (service, registry) => {
    if (service.config.build?.builder !== 'go') return null;
    return createBasePlan({
      service,
      registry,
      builder: 'go',
      runtime: defaultRuntime(service.config.build.runtime, defaultGoRuntime)
    });
  },
  generateDockerfile: plan => renderGoDockerfile(plan),
  validate: plan => {
    assertHasMainInputs(plan);
    assertArtifactsConfigured(plan);
    assertRuntimeCommand(plan);
  }
};
