import { existsSync } from 'fs';
import { resolve } from 'path';
import type { BuildBuilder } from './base';
import {
  assertArtifactsConfigured,
  assertRuntimeCommand,
  createBasePlan,
  defaultRuntime,
  formatContainerWorkdir,
  formatRunStep,
  renderArtifactLines
} from './base';
import {
  collectNxDependents,
  collectNxProjectClosure,
  getNxProjectRoot,
  readNxProjectGraph,
  renderNxRunManyCommand
} from './nx';
import { resolveBuildPaths } from './pathing';
import { ControlError } from '../errors';
import type {
  ControlBuildAutomation,
  GeneratedBuildAutomation,
  GeneratedBuildPath,
  GeneratedBuildPlan
} from '../types';

let defaultNodeRuntime = defaultRuntime(undefined, {
  base_image: 'oven/bun:1.2-alpine',
  packages: [],
  env: {},
  expose: [],
  command: '',
  healthcheck: '',
  user: '',
  workdir: '/app'
});

let renderEnvLines = (plan: GeneratedBuildPlan): string[] => {
  let entries = Object.entries(plan.runtime.env);
  if (entries.length === 0) return [];
  return entries.map(([key, value]) => `ENV ${key}=${JSON.stringify(value)}`);
};

let renderRuntimePackages = (plan: GeneratedBuildPlan): string[] => {
  if (plan.runtime.packages.length === 0) return [];
  return [`RUN apk add --no-cache ${plan.runtime.packages.join(' ')}`];
};

let renderHealthcheckLines = (plan: GeneratedBuildPlan): string[] =>
  plan.runtime.healthcheck
    ? [
        'HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\',
        `  CMD ${plan.runtime.healthcheck}`
      ]
    : [];

let projectPackageJsonPath = (plan: GeneratedBuildPlan, projectRoot: string): GeneratedBuildPath | null => {
  let absolutePath = resolve(plan.contextRoot, projectRoot, 'package.json');
  if (!existsSync(absolutePath)) return null;

  return {
    pattern: `${projectRoot}/package.json`,
    absolutePath,
    relativeToService: projectRoot,
    relativeToContext: `${projectRoot}/package.json`.replace(/\\/g, '/'),
    exists: true
  };
};

let projectRootPath = (plan: GeneratedBuildPlan, projectRoot: string): GeneratedBuildPath => ({
  pattern: projectRoot,
  absolutePath: resolve(plan.contextRoot, projectRoot),
  relativeToService: projectRoot,
  relativeToContext: projectRoot.replace(/\\/g, '/'),
  exists: true
});

let resolveAutomationProjects = (opts: {
  plan: GeneratedBuildPlan;
  automation: ControlBuildAutomation;
  graph: ReturnType<typeof readNxProjectGraph>;
}): string[] => {
  if (opts.automation.kind === 'run-targets') {
    return [...opts.automation.projects].sort((a, b) => a.localeCompare(b));
  }

  return collectNxDependents({
    graph: opts.graph,
    seeds: opts.automation.projects,
    projectFilter: opts.automation.project_filter
  });
};

let renderAutomationCommand = (automation: GeneratedBuildAutomation): string => automation.command;

export let renderNodePrunedDockerfile = (plan: GeneratedBuildPlan): string => {
  let installLinker = plan.service.config.build?.install?.linker ?? 'hoisted';
  let systemPackages = plan.service.config.build?.install?.system_packages ?? ['ca-certificates'];
  let automationLines = plan.automations.map(automation => `RUN cd /app && ${renderAutomationCommand(automation)}`);
  let artifactLines = renderArtifactLines(plan);
  let exposeLines = plan.runtime.expose.map(port => `EXPOSE ${port}`);

  let lines = [
    '# generated by control bootstrap',
    'FROM oven/bun:1.2 AS deps',
    'WORKDIR /app',
    ...(systemPackages.length > 0
      ? [
          'RUN apt-get update && apt-get install -y --no-install-recommends \\',
          ...systemPackages.map((pkg, index) =>
            index === systemPackages.length - 1
              ? `  ${pkg} && rm -rf /var/lib/apt/lists/*`
              : `  ${pkg} \\`
          )
        ]
      : []),
    'COPY _manifests/ ./',
    `RUN bun install --linker=${installLinker}`,
    '',
    'FROM deps AS build',
    'WORKDIR /app',
    'COPY _inputs/ ./',
    ...automationLines,
    `RUN cd /app && bun x nx run ${plan.project}:${plan.target}`,
    '',
    'FROM build AS workspace',
    `WORKDIR ${plan.workspaceRoot}`,
    'CMD ["sleep", "infinity"]',
    '',
    `FROM ${plan.runtime.base_image} AS runner`,
    `WORKDIR ${plan.runtime.workdir}`,
    ...renderRuntimePackages(plan),
    ...artifactLines,
    ...renderEnvLines(plan),
    ...exposeLines,
    ...renderHealthcheckLines(plan),
    `CMD ["sh", "-c", ${JSON.stringify(plan.runtime.command)}]`
  ];

  return lines.filter(Boolean).join('\n') + '\n';
};

export let nodeBuildBuilder: BuildBuilder = {
  kind: 'node',
  plan: (service, registry) => {
    if (service.config.build?.builder !== 'node') return null;

    let runtime = defaultRuntime(service.config.build.runtime, defaultNodeRuntime);
    let plan = createBasePlan({
      service,
      registry,
      builder: 'node',
      runtime
    });
    if (!plan) return null;

    let build = service.config.build;
    if (!build?.project || !build.target) {
      throw new ControlError({
        code: 'node_build_missing_project_target',
        message: `Node service "${service.name}" must declare [build].project and [build].target`
      });
    }

    if (build.manifests?.files?.length || build.inputs?.paths?.length || build.inputs?.include_paths?.length || build.inputs?.generated_paths?.length) {
      throw new ControlError({
        code: 'node_build_legacy_paths_not_supported',
        message: `Node service "${service.name}" still uses legacy [build.manifests] or [build.inputs] path configuration`,
        hint: 'Patch control.toml to use build.project/build.target/build.automations/build.extra_paths'
      });
    }

    if (build.codegen?.steps?.length || build.prebuild?.steps?.length || build.main?.steps?.length) {
      throw new ControlError({
        code: 'node_build_legacy_steps_not_supported',
        message: `Node service "${service.name}" still uses legacy [build.codegen], [build.prebuild], or [build.main] steps`,
        hint: 'Move Node build prerequisites into build.automations and keep the main build in build.target'
      });
    }

    let graph = readNxProjectGraph(plan.contextRoot);
    let mainClosure = collectNxProjectClosure(graph, [build.project]);
    let includedProjects = new Set<string>(mainClosure);
    let resolvedAutomations: GeneratedBuildAutomation[] = [];

    for (let automation of build.automations ?? []) {
      let projects = resolveAutomationProjects({ plan, automation, graph });
      for (let project of collectNxProjectClosure(graph, projects)) {
        includedProjects.add(project);
      }
      resolvedAutomations.push({
        name: automation.name,
        kind: automation.kind,
        target: automation.target,
        projects,
        command: renderNxRunManyCommand({ target: automation.target, projects })
      });
    }

    let manifestFiles = [...includedProjects]
      .sort((a, b) => a.localeCompare(b))
      .map(project => projectPackageJsonPath(plan, getNxProjectRoot(graph, project)))
      .filter((path): path is GeneratedBuildPath => !!path);

    let inputPaths = [...includedProjects]
      .sort((a, b) => a.localeCompare(b))
      .map(project => projectRootPath(plan, getNxProjectRoot(graph, project)));

    let extraPaths = resolveBuildPaths({
      service,
      registry,
      contextRoot: plan.contextRoot,
      patterns: build.extra_paths,
      label: 'extra path'
    });

    for (let extraPath of extraPaths) {
      inputPaths.push(extraPath);
    }

    plan.project = build.project;
    plan.target = build.target;
    plan.manifestFiles = manifestFiles.sort((a, b) => a.relativeToContext.localeCompare(b.relativeToContext));
    plan.inputPaths = inputPaths.sort((a, b) => a.relativeToContext.localeCompare(b.relativeToContext));
    plan.automations = resolvedAutomations;
    plan.codegenSteps = [];
    plan.prebuildSteps = [];
    plan.mainSteps = [];

    return plan;
  },
  generateDockerfile: plan => renderNodePrunedDockerfile(plan),
  validate: plan => {
    if (!plan.project || !plan.target) {
      throw new ControlError({
        code: 'node_build_missing_project_target',
        message: `Node service "${plan.service.name}" must declare build.project and build.target`
      });
    }
    if (plan.inputPaths.length === 0) {
      throw new ControlError({
        code: 'node_build_missing_projects',
        message: `Node service "${plan.service.name}" resolved to an empty Nx build closure`
      });
    }
    assertArtifactsConfigured(plan);
    assertRuntimeCommand(plan);
  }
};
