import type { BuildBuilder } from './base';
import {
  assertArtifactsConfigured,
  assertHasMainInputs,
  assertRuntimeCommand,
  buildCommandForPlan,
  createBasePlan,
  defaultRuntime,
  formatContainerWorkdir,
  formatRunStep,
  renderArtifactLines,
  renderCopyLines
} from './base';
import type { GeneratedBuildPlan } from '../types';

let defaultRustRuntime = defaultRuntime(undefined, {
  base_image: 'debian:trixie-slim',
  packages: ['ca-certificates'],
  env: {},
  expose: [],
  command: '',
  healthcheck: '',
  user: '',
  workdir: '/app'
});

let renderAptPackages = (packages: string[]): string[] => {
  if (packages.length === 0) return [];
  return [
    'RUN apt-get update && apt-get install -y --no-install-recommends \\',
    ...packages.map((pkg, index) =>
      index === packages.length - 1 ? `  ${pkg} && rm -rf /var/lib/apt/lists/*` : `  ${pkg} \\`
    )
  ];
};

let renderRustDockerfile = (plan: GeneratedBuildPlan): string => {
  let builderImage = plan.service.config.build?.builder_image?.image ?? 'rust:1.91-slim';
  let systemPackages = plan.service.config.build?.install?.system_packages ?? ['pkg-config', 'libssl-dev'];
  let manifestLines = renderCopyLines(plan.manifestFiles);
  let inputLines = renderCopyLines(plan.inputPaths);
  let prebuildLines = plan.prebuildSteps.map(step => {
    let cwd = formatContainerWorkdir(step.cwdRelativeToContext ?? '.');
    return `RUN cd ${cwd} && ${formatRunStep(step.run)}`;
  });
  let artifactLines = renderArtifactLines(plan);
  let runtimePackageLines = renderAptPackages(plan.runtime.packages);
  let exposeLines = plan.runtime.expose.map(port => `EXPOSE ${port}`);
  let healthcheckLines = plan.runtime.healthcheck
    ? [
        'HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\',
        `  CMD ${plan.runtime.healthcheck}`
      ]
    : [];
  let envLines = Object.entries(plan.runtime.env).map(([key, value]) => `ENV ${key}=${JSON.stringify(value)}`);

  let lines = [
    '# generated by control bootstrap',
    `FROM ${builderImage} AS builder-base`,
    'WORKDIR /app',
    ...renderAptPackages(systemPackages),
    '',
    'FROM builder-base AS deps',
    'WORKDIR /app',
    ...manifestLines,
    ...prebuildLines,
    '',
    'FROM deps AS build',
    'WORKDIR /app',
    ...inputLines,
    `RUN cd ${plan.workspaceRoot} && ${buildCommandForPlan(plan)}`,
    '',
    'FROM build AS workspace',
    `WORKDIR ${plan.workspaceRoot}`,
    'CMD ["sleep", "infinity"]',
    '',
    `FROM ${plan.runtime.base_image} AS runner`,
    `WORKDIR ${plan.runtime.workdir}`,
    ...runtimePackageLines,
    ...artifactLines,
    ...envLines,
    ...exposeLines,
    ...healthcheckLines,
    ...(plan.runtime.user ? [`USER ${plan.runtime.user}`] : []),
    `CMD ${JSON.stringify([plan.runtime.command])}`
  ];

  return lines.filter(Boolean).join('\n') + '\n';
};

export let rustBuildBuilder: BuildBuilder = {
  kind: 'rust',
  plan: (service, registry) => {
    if (service.config.build?.builder !== 'rust') return null;
    return createBasePlan({
      service,
      registry,
      builder: 'rust',
      runtime: defaultRuntime(service.config.build.runtime, defaultRustRuntime)
    });
  },
  generateDockerfile: plan => renderRustDockerfile(plan),
  validate: plan => {
    assertHasMainInputs(plan);
    assertArtifactsConfigured(plan);
    assertRuntimeCommand(plan);
  }
};
