import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { ControlError } from './errors';
import { collectBuildPlans, renderDockerfileForPlan } from './builders';
import { resolveControlCwd } from './entrypoint';
import { getRegistry } from './registry';

type BootstrapResult = {
  changed: string[];
  checked: string[];
  printed: string[];
};

let GENERATED_HEADER = '# generated by control bootstrap';

let createNxConfig = (scope: 'repo' | 'oss' = 'repo') => ({
  $schema: './node_modules/nx/schemas/nx-schema.json',
  namedInputs: {
    default: ['{projectRoot}/**/*', 'sharedGlobals'],
    production: [
      'default',
      '!{projectRoot}/dist/**',
      '!{projectRoot}/coverage/**',
      '!{projectRoot}/.control/**',
      '!{projectRoot}/generated/**',
      '!{projectRoot}/prisma/generated/**',
      '!{projectRoot}/src/generated/**',
      '!{projectRoot}/node_modules/.prisma/**',
      '!{projectRoot}/node_modules/@prisma/**'
    ],
    clientProduction: [
      '{projectRoot}/**/*',
      '!{projectRoot}/dist/**',
      '!{projectRoot}/coverage/**',
      '!{projectRoot}/.control/**',
      ...(scope === 'repo'
        ? ['{workspaceRoot}/bun.lock', '{workspaceRoot}/oss/bun.lock']
        : ['{workspaceRoot}/bun.lock'])
    ],
    sharedGlobals:
      scope === 'repo'
        ? [
            '{workspaceRoot}/package.json',
            '{workspaceRoot}/bun.lock',
            '{workspaceRoot}/oss/package.json',
            '{workspaceRoot}/oss/bun.lock'
          ]
        : ['{workspaceRoot}/package.json', '{workspaceRoot}/bun.lock']
  },
  targetDefaults: {
    build: {
      cache: true,
      dependsOn: ['^build'],
      inputs: ['production', '^production'],
      outputs: ['{projectRoot}/dist/**']
    },
    'server:build': {
      cache: true,
      dependsOn: ['prisma:generate', '^build'],
      inputs: ['production', '^production'],
      outputs: ['{projectRoot}/dist/**']
    },
    'frontend:build': {
      cache: true,
      dependsOn: ['^build'],
      inputs: ['production', '^production'],
      outputs: ['{projectRoot}/dist/**', '{projectRoot}/frontend/dist/**', '{projectRoot}/frontend/**/dist/**']
    },
    'worker:build': {
      cache: true,
      dependsOn: ['prisma:generate', '^build'],
      inputs: ['production', '^production'],
      outputs: ['{projectRoot}/dist-worker/**']
    },
    test: {
      cache: false,
      inputs: ['default', '^production']
    },
    'test:unit': {
      cache: true,
      inputs: ['production', '^production'],
      outputs: ['{projectRoot}/coverage/**']
    },
    'check-types': {
      cache: true,
      dependsOn: ['^check-types'],
      inputs: ['production', '^production']
    },
    'prisma:generate': {
      cache: true,
      dependsOn: ['^prisma:generate'],
      inputs: ['production', '^production'],
      outputs: [
        '{projectRoot}/node_modules/.prisma/**',
        '{projectRoot}/node_modules/@prisma/**',
        '{projectRoot}/generated/**',
        '{projectRoot}/prisma/generated/**',
        '{projectRoot}/src/generated/**',
        '{workspaceRoot}/node_modules/.prisma/**',
        '{workspaceRoot}/node_modules/@prisma/**'
      ]
    },
    'prisma:push': {
      cache: false
    },
    dev: {
      cache: false
    },
    deploy: {
      cache: false
    }
  }
});

let renderNxJson = (scope: 'repo' | 'oss' = 'repo'): string =>
  JSON.stringify(createNxConfig(scope), null, 2) + '\n';

let ensureFileState = (opts: {
  path: string;
  content: string;
  check?: boolean;
  print?: boolean;
}): { changed: boolean; printed?: string } => {
  let current = existsSync(opts.path) ? readFileSync(opts.path, 'utf8') : '';

  if (opts.print) {
    return {
      changed: current !== opts.content,
      printed: [`# ${opts.path}`, opts.content].join('\n')
    };
  }

  if (opts.check) {
    if (current !== opts.content) {
      throw new ControlError({
        code: 'bootstrap_out_of_date',
        message: `Generated file is out of date: ${opts.path}`,
        hint: 'Run `control bootstrap` to refresh generated files'
      });
    }
    return { changed: false };
  }

  if (current !== opts.content) {
    mkdirSync(dirname(opts.path), { recursive: true });
    writeFileSync(opts.path, opts.content);
    return { changed: true };
  }

  return { changed: false };
};

export let runBootstrap = async (opts?: {
  entrypoint?: string;
  check?: boolean;
  print?: boolean;
  service?: string;
}) => {
  let cwd = resolveControlCwd();
  let registry = getRegistry({ cwd, entrypoint: opts?.entrypoint });
  let plans = collectBuildPlans(registry, opts?.service);
  let result: BootstrapResult = { changed: [], checked: [], printed: [] };

  let nxPath = resolve(registry.controlRoot, 'nx.json');
  let nxState = ensureFileState({
    path: nxPath,
    content: renderNxJson('repo'),
    check: opts?.check,
    print: opts?.print
  });

  if (opts?.print && nxState.printed) result.printed.push(nxState.printed);
  if (nxState.changed) result.changed.push(nxPath);
  result.checked.push(nxPath);

  let ossNxPath = resolve(registry.ossRoot, 'nx.json');
  let ossNxState = ensureFileState({
    path: ossNxPath,
    content: renderNxJson('oss'),
    check: opts?.check,
    print: opts?.print
  });

  if (opts?.print && ossNxState.printed) result.printed.push(ossNxState.printed);
  if (ossNxState.changed) result.changed.push(ossNxPath);
  result.checked.push(ossNxPath);

  for (let plan of plans) {
    let content = renderDockerfileForPlan(plan);
    let state = ensureFileState({
      path: plan.dockerfilePath,
      content,
      check: opts?.check,
      print: opts?.print
    });

    if (opts?.print && state.printed) result.printed.push(state.printed);
    if (state.changed) result.changed.push(plan.dockerfilePath);
    result.checked.push(plan.dockerfilePath);
  }

  if (opts?.print) {
    console.log(result.printed.join('\n\n'));
    return;
  }

  if (opts?.check) {
    console.log(`Checked ${result.checked.length} generated file(s)`);
    return;
  }

  console.log(`Updated ${result.changed.length} generated file(s)`);
  for (let file of result.changed) {
    console.log(` - ${file}`);
  }
};
