import type { ResolvedDatabase } from '../types';

export let generatePostgresInitScript = (databases: ResolvedDatabase[]): string => {
  if (databases.length === 0) return '';

  let names = databases.map(db => db.name);
  let lines = [
    '#!/bin/sh',
    'set -e',
    '',
    `# Generated by control — creates ${names.length} database(s)`,
    `dbs="${names.join(' ')}"`,
    'for db in $dbs; do',
    '  exists=$(psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \\',
    '    -tAc "SELECT 1 FROM pg_database WHERE datname=\'${db}\'")',
    '  if [ "$exists" != "1" ]; then',
    '    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \\',
    '      -c "CREATE DATABASE \\"${db}\\";"',
    '  fi',
    'done',
    '',
    'echo "Database initialization complete"'
  ];

  return lines.join('\n') + '\n';
};
