export let DEFAULT_ALERT_FILTER_COUNT_THRESHOLD = 2;
export let DEFAULT_ALERT_CONFIDENCE_THRESHOLD = 0.7;
export let MAX_SCAN_TARGETS = 100;
export let MAX_SCAN_TARGET_LENGTH = 20_000;
export let SAMPLE_BUFFER_LINES = 2;
