name = "@metorial-cargo/service"
group = "oss"

[[dependencies]]
identifier = "@metorial/object-storage"
env = [{ endpoint = "rpc", key = "OBJECT_STORAGE_URL", value = "http://{{HOSTNAME}}:{{PORT}}" }]

[[dependencies]]
identifier = "@metorial/origin"
env = [{ endpoint = "api", key = "ORIGIN_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-origin" }]

[[dependencies]]
identifier = "@metorial/code-bucket-service-generated"
env = [{ endpoint = "rpc", key = "CODE_BUCKET_SERVICE_URL", value = "{{HOSTNAME}}:{{PORT}}" }]

[[dependencies]]
identifier = "@metorial/voyager"
env = [{ endpoint = "rpc", key = "VOYAGER_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-voyager" }]

[dev]
run = ["bun --watch ./src/server.ts"]

[endpoints.api]
port = 52150
env = [{ key = "CARGO_API_PORT", value = "{{PORT}}" }]

[endpoints.content]
port = 52151
env = [
  { key = "CARGO_CONTENT_PORT", value = "{{PORT}}" },
  { key = "DOWNLOAD_PUBLIC_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[endpoints.health]
port = 12121
env = [{ key = "CARGO_HEALTH_PORT", value = "{{PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
FILES_BUCKET_NAME = "mte-files"
CARGO_REGION = "dev"
SIGNED_DOWNLOAD_URL_TOKEN_SECRET = "dev-cargo-download-token-secret"
API_URL = "http://localhost:4310"

[dev.db.main]
name = "cargo"
engine = "postgres"
env = "DATABASE_URL"
