name = "@metorial-cargo/service"
group = "oss"

[dev]
prepare = ["bun run prisma:generate", "bun run prisma:push"]
run = ["bun --watch ./src/server.ts"]

[[dev.expose]]
port = 52150

[[dev.expose]]
port = 52151

[[dev.expose]]
port = 12121

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
REDIS_URL = "redis://localhost:36379/0"
OBJECT_STORAGE_URL = "http://services:52010"
FILES_BUCKET_NAME = "mte-files"
DOWNLOAD_PUBLIC_URL = "http://{{HOSTNAME}}:52151"
CARGO_REGION = "dev"
SIGNED_DOWNLOAD_URL_TOKEN_SECRET = "dev-cargo-download-token-secret"
CARGO_API_PORT = "52150"
CARGO_CONTENT_PORT = "52151"
CARGO_HEALTH_PORT = "12121"
API_URL = "http://{{HOSTNAME}}:4310"
ORIGIN_URL = "http://{{HOSTNAME}}:52090/metorial-origin"
CODE_BUCKET_SERVICE_URL = "localhost:5050"
VOYAGER_URL = "http://{{HOSTNAME}}:52060/metorial-voyager"

[dev.db.main]
name = "cargo"
engine = "postgres"
env = "DATABASE_URL"
