name: Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'src/systems/shuttle/service/**'
      - 'src/systems/shuttle/clients/**'
      - 'src/systems/shuttle/sdk/**'
      - 'src/systems/_clients/shuttle/**'
      - 'src/systems/shuttle/.github/workflows/publish.yml'
      - '.github/workflows/system-build-image.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/systems/shuttle/service/**'
      - 'src/systems/shuttle/clients/**'
      - 'src/systems/shuttle/sdk/**'
      - 'src/systems/_clients/shuttle/**'
      - 'src/systems/shuttle/.github/workflows/publish.yml'
      - '.github/workflows/system-build-image.yml'

jobs:
  build-and-publish-docker:
    uses: ./.github/workflows/system-build-image.yml
    secrets: inherit
    with:
      image_name: metorial/shuttle
      docker_context: ./src/systems/shuttle/service
      dockerfile: ./src/systems/shuttle/service/Dockerfile
      runner: depot-ubuntu-24.04-4
