name = "@metorial/signal"
group = "oss"

[[dependencies]]
identifier = "@metorial/object-storage"
env = [
  { endpoint = "rpc", key = "OBJECT_STORAGE_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[test.e2e]
start = ["test:start-e2e"]

[dev]
run = ["dev:start"]

[endpoints.api]
port = 52050
env = [{ key = "SIGNAL_API_PORT", value = "{{PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
LOGS_BUCKET_NAME = "signal-logs"

[dev.db.main]
package = "@metorial/signal"
name = "signal"
engine = "postgres"
env = "DATABASE_URL"
