name = "@metorial/code-bucket-service-generated"
group = "oss"

[[dependencies]]
identifier = "@metorial/object-storage"
env = [
  { endpoint = "rpc", key = "CODE_BUCKET_OBJECT_STORAGE_ENDPOINT", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[test.e2e]
start = ["make run"]

[dev]
run = ["make dev"]

[endpoints.http]
port = 52091
env = [
  { key = "CODE_BUCKET_HTTP_ADDRESS", value = ":{{PORT}}" },
  { key = "CODE_BUCKET_EDITOR_API_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[endpoints.workspace]
port = 52092
env = [{ key = "CODE_BUCKET_WORKSPACE_ADDRESS", value = ":{{PORT}}" }]

[endpoints.rpc]
port = 5050
env = [{ key = "CODE_BUCKET_RPC_ADDRESS", value = ":{{PORT}}" }]

[[resources]]
type = "redis"
env = [
  { key = "CODE_BUCKET_REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" },
]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
CODE_BUCKET_JWT_SECRET = "origin-code-bucket-dev-secret"
CODE_BUCKET_OBJECT_STORAGE_BUCKET = "code-bucket"
