name = "@metorial/code-bucket-service-generated"
group = "oss"

[dev]
run = ["make dev"]

[[dev.expose]]
port = 52091

[[dev.expose]]
port = 52092

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
CODE_BUCKET_JWT_SECRET = "origin-code-bucket-dev-secret"
CODE_BUCKET_OBJECT_STORAGE_ENDPOINT = "http://services:52010"
CODE_BUCKET_OBJECT_STORAGE_BUCKET = "code-bucket"
CODE_BUCKET_REDIS_URL = "redis://localhost:36379/0"
CODE_BUCKET_HTTP_ADDRESS = ":52091"
CODE_BUCKET_RPC_ADDRESS = ":5050"
CODE_BUCKET_WORKSPACE_ADDRESS = ":52092"
CODE_BUCKET_EDITOR_API_URL = "http://localhost:52091"
