name = "@metorial/function-bay"
group = "oss"

[dev]
run = ["bun --watch ./src/server.ts"]

[[dev.expose]]
port = 52030

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
REDIS_URL = "redis://localhost:{{CONTROL_PORT_REDIS}}/0"
ENCRYPTION_KEY = "sTrG+z8ewVo7JJsgmv39UL/YDdgxlHSVhVPJOV7Omdg"
DEFAULT_PROVIDER = "local"
OBJECT_STORAGE_URL = "http://services:52010"
BUNDLE_BUCKET_NAME = "function-bay-bundles"
FORGE_API_URL = "http://localhost:52020/metorial-forge"

[dev.db.main]
name = "function-bay"
engine = "postgres"
env = "DATABASE_URL"
