name = "@metorial/function-bay"
group = "oss"

[[dependencies]]
identifier = "@metorial/forge"
env = [
  { endpoint = "api", key = "FORGE_API_URL", value = "http://{{HOSTNAME}}:{{PORT}}/metorial-forge" },
]

[dev]
run = ["dev:start"]

[endpoints.api]
port = 52030
env = [{ key = "FUNCTION_BAY_API_PORT", value = "{{BIND_PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
ENCRYPTION_KEY = "sTrG+z8ewVo7JJsgmv39UL/YDdgxlHSVhVPJOV7Omdg"
DEFAULT_PROVIDER = "local"
OBJECT_STORAGE_URL = "http://services:52010"
BUNDLE_BUCKET_NAME = "function-bay-bundles"

[dev.db.main]
package = "@metorial/function-bay"
name = "function-bay"
engine = "postgres"
env = "DATABASE_URL"
