name = "@metorial/forge"
group = "oss"

[dev]
prepare = ["bun run prisma:generate", "bun run prisma:push"]
run = ["bun --watch ./src/server.ts"]

[[dev.expose]]
port = 52020

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
REDIS_URL = "redis://localhost:36379/0"
ENCRYPTION_KEY = "sTrG+z8ewVo7JJsgmv39UL/YDdgxlHSVhVPJOV7Omdg"
DEFAULT_PROVIDER = "local"
OBJECT_STORAGE_URL = "http://services:52010"
ARTIFACT_BUCKET_NAME = "artifacts"
LOG_BUCKET_NAME = "logs"

[dev.db.main]
name = "forge"
engine = "postgres"
env = "DATABASE_URL"
