name = "@metorial/forge"
group = "oss"

[[dependencies]]
identifier = "@metorial/object-storage"
env = [
  { endpoint = "rpc", key = "OBJECT_STORAGE_URL", value = "http://{{HOSTNAME}}:{{PORT}}" },
]

[test.e2e]
start = ["bun ./src/server.ts"]

[dev]
run = ["bun --watch ./src/server.ts"]

[endpoints.api]
port = 52020
env = [{ key = "FORGE_API_PORT", value = "{{PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"
ENCRYPTION_KEY = "sTrG+z8ewVo7JJsgmv39UL/YDdgxlHSVhVPJOV7Omdg"
DEFAULT_PROVIDER = "local"
ARTIFACT_BUCKET_NAME = "artifacts"
LOG_BUCKET_NAME = "logs"

[dev.db.main]
name = "forge"
engine = "postgres"
env = "DATABASE_URL"
