name = "@metorial/voyager"
group = "oss"

[test.e2e]
start = ["test:start-e2e"]

[dev]
run = ["dev:start"]

[endpoints.rpc]
port = 52060
env = [{ key = "VOYAGER_PORT", value = "{{BIND_PORT}}" }]

[[resources]]
type = "redis"
env = [{ key = "REDIS_URL", value = "redis://{{HOSTNAME}}:{{PORT}}/0" }]

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"

[dev.db.main]
package = "@metorial/voyager"
name = "voyager"
engine = "postgres"
env = "DATABASE_URL"

[dev.db.search]
package = "@metorial/voyager"
name = "voyager-search"
engine = "postgres"
env = "SEARCH_DATABASE_URL"
