// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto-mcp-manager.proto

package proto_mcp_manager_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerType int32

const (
	WorkerType_WORKER_TYPE_RUNNER WorkerType = 0
)

// Enum value maps for WorkerType.
var (
	WorkerType_name = map[int32]string{
		0: "WORKER_TYPE_RUNNER",
	}
	WorkerType_value = map[string]int32{
		"WORKER_TYPE_RUNNER": 0,
	}
)

func (x WorkerType) Enum() *WorkerType {
	p := new(WorkerType)
	*p = x
	return p
}

func (x WorkerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mcp_manager_proto_enumTypes[0].Descriptor()
}

func (WorkerType) Type() protoreflect.EnumType {
	return &file_proto_mcp_manager_proto_enumTypes[0]
}

func (x WorkerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerType.Descriptor instead.
func (WorkerType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mcp_manager_proto_rawDescGZIP(), []int{0}
}

type ListManagersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagersRequest) Reset() {
	*x = ListManagersRequest{}
	mi := &file_proto_mcp_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagersRequest) ProtoMessage() {}

func (x *ListManagersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagersRequest.ProtoReflect.Descriptor instead.
func (*ListManagersRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_manager_proto_rawDescGZIP(), []int{0}
}

type ListManagersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Managers      []*Manager             `protobuf:"bytes,1,rep,name=managers,proto3" json:"managers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagersResponse) Reset() {
	*x = ListManagersResponse{}
	mi := &file_proto_mcp_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagersResponse) ProtoMessage() {}

func (x *ListManagersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagersResponse.ProtoReflect.Descriptor instead.
func (*ListManagersResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ListManagersResponse) GetManagers() []*Manager {
	if x != nil {
		return x.Managers
	}
	return nil
}

type Manager struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manager) Reset() {
	*x = Manager{}
	mi := &file_proto_mcp_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manager) ProtoMessage() {}

func (x *Manager) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manager.ProtoReflect.Descriptor instead.
func (*Manager) Descriptor() ([]byte, []int) {
	return file_proto_mcp_manager_proto_rawDescGZIP(), []int{2}
}

func (x *Manager) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manager) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	WorkerType    WorkerType             `protobuf:"varint,3,opt,name=worker_type,json=workerType,proto3,enum=proto.WorkerType" json:"worker_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_mcp_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_manager_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterWorkerRequest) GetWorkerType() WorkerType {
	if x != nil {
		return x.WorkerType
	}
	return WorkerType_WORKER_TYPE_RUNNER
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_mcp_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_manager_proto_rawDescGZIP(), []int{4}
}

var File_proto_mcp_manager_proto protoreflect.FileDescriptor

const file_proto_mcp_manager_proto_rawDesc = "" +
	"\n" +
	"\x17proto-mcp-manager.proto\x12\x05proto\"\x15\n" +
	"\x13ListManagersRequest\"B\n" +
	"\x14ListManagersResponse\x12*\n" +
	"\bmanagers\x18\x01 \x03(\v2\x0e.proto.ManagerR\bmanagers\"3\n" +
	"\aManager\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x82\x01\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x122\n" +
	"\vworker_type\x18\x03 \x01(\x0e2\x11.proto.WorkerTypeR\n" +
	"workerType\"\x18\n" +
	"\x16RegisterWorkerResponse*$\n" +
	"\n" +
	"WorkerType\x12\x16\n" +
	"\x12WORKER_TYPE_RUNNER\x10\x002\xad\x01\n" +
	"\x13McpManagerForWorker\x12G\n" +
	"\fListManagers\x12\x1a.proto.ListManagersRequest\x1a\x1b.proto.ListManagersResponse\x12M\n" +
	"\x0eRegisterWorker\x12\x1c.proto.RegisterWorkerRequest\x1a\x1d.proto.RegisterWorkerResponseB\x19Z\x17proto-mcp-manager.protob\x06proto3"

var (
	file_proto_mcp_manager_proto_rawDescOnce sync.Once
	file_proto_mcp_manager_proto_rawDescData []byte
)

func file_proto_mcp_manager_proto_rawDescGZIP() []byte {
	file_proto_mcp_manager_proto_rawDescOnce.Do(func() {
		file_proto_mcp_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mcp_manager_proto_rawDesc), len(file_proto_mcp_manager_proto_rawDesc)))
	})
	return file_proto_mcp_manager_proto_rawDescData
}

var file_proto_mcp_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mcp_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_mcp_manager_proto_goTypes = []any{
	(WorkerType)(0),                // 0: proto.WorkerType
	(*ListManagersRequest)(nil),    // 1: proto.ListManagersRequest
	(*ListManagersResponse)(nil),   // 2: proto.ListManagersResponse
	(*Manager)(nil),                // 3: proto.Manager
	(*RegisterWorkerRequest)(nil),  // 4: proto.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 5: proto.RegisterWorkerResponse
}
var file_proto_mcp_manager_proto_depIdxs = []int32{
	3, // 0: proto.ListManagersResponse.managers:type_name -> proto.Manager
	0, // 1: proto.RegisterWorkerRequest.worker_type:type_name -> proto.WorkerType
	1, // 2: proto.McpManagerForWorker.ListManagers:input_type -> proto.ListManagersRequest
	4, // 3: proto.McpManagerForWorker.RegisterWorker:input_type -> proto.RegisterWorkerRequest
	2, // 4: proto.McpManagerForWorker.ListManagers:output_type -> proto.ListManagersResponse
	5, // 5: proto.McpManagerForWorker.RegisterWorker:output_type -> proto.RegisterWorkerResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mcp_manager_proto_init() }
func file_proto_mcp_manager_proto_init() {
	if File_proto_mcp_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mcp_manager_proto_rawDesc), len(file_proto_mcp_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mcp_manager_proto_goTypes,
		DependencyIndexes: file_proto_mcp_manager_proto_depIdxs,
		EnumInfos:         file_proto_mcp_manager_proto_enumTypes,
		MessageInfos:      file_proto_mcp_manager_proto_msgTypes,
	}.Build()
	File_proto_mcp_manager_proto = out.File
	file_proto_mcp_manager_proto_goTypes = nil
	file_proto_mcp_manager_proto_depIdxs = nil
}
