name = "@metorial-subspace/db"
group = "oss"

[dev.env]
METORIAL_ENV = "development"
METORIAL_SOURCE = "oss"
IS_ENTERPRISE = "false"
METORIAL_HOSTNAME = "{{HOSTNAME}}"
NODE_ENV = "development"

[dev.db.main]
name = "subspace"
engine = "postgres"
env = "DATABASE_URL"
