import { Instance, MagicMcpServerStatus, Organization, OrganizationActor } from '@metorial/db';
import { badRequestError, ServiceError } from '@metorial/error';
import { serverService } from '@metorial/module-catalog';
import { magicMcpServerService } from '@metorial/module-magic';
import {
  customProviderService,
  subspaceProviderDeploymentService,
  subspaceProviderListingService,
  subspaceSessionTemplateService
} from '@metorial/module-subspace';
import { Paginator } from '@metorial/pagination';
import { Controller } from '@metorial/rest';
import { v } from '@metorial/validation';
import { normalizeArrayParam } from '../../lib/normalizeArrayParam';
import { checkAccess } from '../../middleware/checkAccess';
import { hasFlags } from '../../middleware/hasFlags';
import { instanceGroup, instancePath } from '../../middleware/instanceGroup';
import { magicMcpServerPresenter } from '../../presenters';

type MagicMcpServerWithRelations = Awaited<
  ReturnType<typeof magicMcpServerService.getMagicMcpServerById>
>;
type MagicMcpServerWithSessionTemplate = MagicMcpServerWithRelations & {
  sessionTemplate: {
    id: string;
    name: string | null;
    description: string | null;
  } | null;
};

let withSessionTemplate = async (
  ctx: {
    instance: Instance;
    organization: Organization;
  },
  magicMcpServer: MagicMcpServerWithRelations
): Promise<MagicMcpServerWithSessionTemplate> => {
  let sessionTemplate = await subspaceSessionTemplateService
    .get({
      instance: ctx.instance,
      organization: ctx.organization,
      sessionTemplateId: magicMcpServer.subspaceSessionTemplateId
    })
    .catch(() => null);

  return {
    ...magicMcpServer,
    sessionTemplate: sessionTemplate
      ? {
          id: sessionTemplate.id,
          name: sessionTemplate.name,
          description: sessionTemplate.description
        }
      : null
  };
};

let sleep = async (ms: number) => {
  await new Promise(resolve => setTimeout(resolve, ms));
};

let createSessionTemplateFromServer = async (d: {
  instance: Instance;
  organization: Organization;
  performedBy: OrganizationActor;
  serverId: string;
  serverVariantId?: string;
  name: string;
  description?: string;
  metadata?: Record<string, unknown>;
  config?: Record<string, unknown>;
}) => {
  let server = await serverService.getServerById({
    serverId: d.serverId,
    organization: d.organization
  });

  let variant = d.serverVariantId
    ? server.variants.find(v => v.id === d.serverVariantId)
    : (server.variants.find(v => v.isDefault) ?? server.variants[0]);

  if (!variant) {
    throw new ServiceError(
      badRequestError({
        message: 'The selected server does not have a deployable variant.'
      })
    );
  }

  if (variant.sourceType === 'managed') {
    throw new ServiceError(
      badRequestError({
        message:
          'Automatic Magic MCP setup is not supported for managed servers. Please provide session_template_id.'
      })
    );
  }

  let deployment: Awaited<ReturnType<typeof subspaceProviderDeploymentService.create>>;

  if (variant.remoteUrl || variant.dockerImage) {
    let from = variant.remoteUrl
      ? {
          type: 'remote' as const,
          remoteUrl: variant.remoteUrl,
          protocol: variant.remoteServerProtocol
        }
      : {
          type: 'container' as const,
          repository: {
            imageRef: variant.dockerImage!,
            username: undefined,
            password: undefined
          }
        };

    let customProvider = await customProviderService.create({
      instance: d.instance,
      organization: d.organization,
      organizationActor: d.performedBy,
      name: `${d.name} Provider`,
      description: d.description ?? `Autogenerated provider for ${d.name}`,
      metadata: {
        ...(d.metadata ?? {}),
        source: 'magic_mcp_server',
        sourceServerId: server.id,
        sourceServerVariantId: variant.id
      },
      from
    });

    let providerId = customProvider.provider?.id;
    let providerVersionId = customProvider.provider?.currentVersion?.id;

    for (let attempt = 0; attempt < 20 && (!providerId || !providerVersionId); attempt++) {
      await sleep(500);

      let fresh = await customProviderService.get({
        instance: d.instance,
        organization: d.organization,
        customProviderId: customProvider.id
      });

      providerId = fresh.provider?.id ?? providerId;
      providerVersionId = fresh.provider?.currentVersion?.id ?? providerVersionId;
    }

    if (!providerId) {
      throw new ServiceError(
        badRequestError({
          message: `Failed to prepare the provider for this server (${variant.sourceType}). Please try again in a moment.`
        })
      );
    }

    deployment = await subspaceProviderDeploymentService.create({
      instance: d.instance,
      organization: d.organization,
      organizationActor: d.performedBy,
      name: `${d.name} Deployment`,
      description: d.description ?? `Autogenerated deployment for ${d.name}`,
      metadata: {
        ...(d.metadata ?? {}),
        source: 'magic_mcp_server',
        sourceServerId: server.id,
        sourceServerVariantId: variant.id
      },
      providerId,
      lockedProviderVersionId: providerVersionId,
      config: {
        type: 'inline',
        data: d.config ?? {}
      }
    });
  } else {
    let searchTerms = [
      server.importedServer?.identifier,
      server.importedServer?.slug,
      server.name
    ].filter((term): term is string => !!term && term.length > 0);

    let providerListings: Awaited<
      ReturnType<typeof subspaceProviderListingService.list>
    >['items'] = [];
    let seenProviderListingIds = new Set<string>();

    for (let search of searchTerms) {
      let result = await subspaceProviderListingService.list({
        instance: d.instance,
        organization: d.organization,
        search,
        limit: 20
      });

      for (let item of result.items) {
        if (seenProviderListingIds.has(item.id)) continue;
        seenProviderListingIds.add(item.id);
        providerListings.push(item);
      }
    }

    let normalizedCandidates = new Set(
      [
        server.name,
        server.importedServer?.name,
        server.importedServer?.identifier,
        server.importedServer?.slug,
        variant.identifier
      ]
        .filter((value): value is string => !!value && value.length > 0)
        .map(value => value.toLowerCase().replace(/[^a-z0-9]/g, ''))
    );

    let bestListing =
      providerListings.find((item: (typeof providerListings)[number]) => {
        let byName = item.name.toLowerCase().replace(/[^a-z0-9]/g, '');
        let bySlug = item.slug.toLowerCase().replace(/[^a-z0-9]/g, '');
        let byIdentifier = item.provider.identifier.toLowerCase().replace(/[^a-z0-9]/g, '');

        return (
          normalizedCandidates.has(byName) ||
          normalizedCandidates.has(bySlug) ||
          normalizedCandidates.has(byIdentifier)
        );
      }) ?? providerListings[0];

    if (!bestListing) {
      throw new ServiceError(
        badRequestError({
          message:
            'Automatic Magic MCP setup is unavailable for this server right now. Please configure a session template manually.'
        })
      );
    }

    deployment = await subspaceProviderDeploymentService.create({
      instance: d.instance,
      organization: d.organization,
      organizationActor: d.performedBy,
      name: `${d.name} Deployment`,
      description: d.description ?? `Autogenerated deployment for ${d.name}`,
      metadata: {
        ...(d.metadata ?? {}),
        source: 'magic_mcp_server',
        sourceServerId: server.id,
        sourceServerVariantId: variant.id,
        sourceProviderListingId: bestListing.id
      },
      providerId: bestListing.provider.id,
      lockedProviderVersionId: bestListing.provider.currentVersion?.id,
      config: {
        type: 'inline',
        data: d.config ?? {}
      }
    });
  }

  if (!variant.remoteUrl && !deployment) {
    throw new ServiceError(
      badRequestError({
        message: 'Failed to create a provider deployment for this server.'
      })
    );
  }

  return await subspaceSessionTemplateService.create({
    instance: d.instance,
    organization: d.organization,
    organizationActor: d.performedBy,
    name: d.name,
    description: d.description ?? `Autogenerated session template for ${d.name}`,
    metadata: {
      ...(d.metadata ?? {}),
      source: 'magic_mcp_server',
      sourceServerId: server.id,
      sourceServerVariantId: variant.id
    },
    providers: [
      {
        providerDeploymentId: deployment.id
      }
    ]
  });
};

export let magicMcpServerGroup = instanceGroup.use(async ctx => {
  if (!ctx.params.magicMcpServerId) throw new Error('magicMcpServerId is required');

  let magicMcpServer = await magicMcpServerService.getMagicMcpServerById({
    magicMcpServerId: ctx.params.magicMcpServerId,
    instance: ctx.instance,
    accessTags: ctx.accessTags
  });

  return { magicMcpServer };
});

let createMagicMcpServerBaseSchema = v.object({
  name: v.string(),
  description: v.optional(v.string()),
  metadata: v.optional(v.record(v.any())),
  config: v.optional(v.record(v.any())),
  session_template_id: v.optional(v.string()),
  server_id: v.optional(v.string()),
  server_variant_id: v.optional(v.string())
});
export let createMagicMcpServerSchema = createMagicMcpServerBaseSchema;

let magicMcpServerStatusValues: ['active', 'archived', 'deleted'] = [
  'active',
  'archived',
  'deleted'
];

export let magicMcpServerController = Controller.create(
  {
    name: 'Magic MCP Server',
    description:
      'Before you can connect to an MCP server, you need to create a magic MCP server.'
  },
  {
    list: instanceGroup
      .get(instancePath('magic-mcp-servers', 'magicMcpServers.list'), {
        name: 'List magic MCP server',
        description: 'List all magic MCP server'
      })
      .use(
        checkAccess({
          possibleScopes: [
            'instance.server.deployment:read',
            'consumer#instance.magic_mcp:read'
          ]
        })
      )
      .outputList(magicMcpServerPresenter)
      .query(
        'default',
        Paginator.validate(
          v.object({
            status: v.optional(
              v.union([
                v.enumOf(magicMcpServerStatusValues),
                v.array(v.enumOf(magicMcpServerStatusValues))
              ])
            ),
            magic_mcp_group_id: v.optional(v.union([v.string(), v.array(v.string())])),
            search: v.optional(v.string())
          })
        )
      )
      .use(hasFlags(['magic-mcp-enabled']))
      .do(async ctx => {
        let paginator = await magicMcpServerService.listMagicMcpServers({
          instance: ctx.instance,
          status: normalizeArrayParam<MagicMcpServerStatus>(ctx.query.status),
          groupIds: normalizeArrayParam(ctx.query.magic_mcp_group_id),
          search: ctx.query.search,
          accessTags: ctx.accessTags
        });

        let list = await paginator.run(ctx.query);
        let hydrated = await Promise.all(
          list.items.map(server => withSessionTemplate(ctx, server))
        );

        return Paginator.present(
          {
            ...list,
            items: hydrated
          },
          magicMcpServer => magicMcpServerPresenter.present({ magicMcpServer })
        );
      }),

    get: magicMcpServerGroup
      .get(instancePath('magic-mcp-servers/:magicMcpServerId', 'magicMcpServers.get'), {
        name: 'Get magic MCP server',
        description: 'Get the information of a specific magic MCP server'
      })
      .use(
        checkAccess({
          possibleScopes: [
            'instance.server.deployment:read',
            'consumer#instance.magic_mcp:read'
          ]
        })
      )
      .output(magicMcpServerPresenter)
      .use(hasFlags(['magic-mcp-enabled']))
      .do(async ctx => {
        return magicMcpServerPresenter.present({
          magicMcpServer: await withSessionTemplate(ctx, ctx.magicMcpServer)
        });
      }),

    create: instanceGroup
      .post(instancePath('magic-mcp-servers', 'magicMcpServers.create'), {
        name: 'Create magic MCP server',
        description: 'Create a new magic MCP server'
      })
      .use(
        checkAccess({
          possibleScopes: [
            'instance.server.deployment:write',
            'consumer#instance.magic_mcp:write'
          ]
        })
      )
      .body('default', createMagicMcpServerSchema)
      .output(magicMcpServerPresenter)
      .use(hasFlags(['magic-mcp-enabled']))
      .do(async ctx => {
        if (!ctx.body.session_template_id && !ctx.body.server_id) {
          throw new ServiceError(
            badRequestError({
              message: 'Either session_template_id or server_id must be provided.'
            })
          );
        }

        let sessionTemplate = ctx.body.session_template_id
          ? await subspaceSessionTemplateService.get({
              instance: ctx.instance,
              organization: ctx.organization,
              sessionTemplateId: ctx.body.session_template_id
            })
          : await createSessionTemplateFromServer({
              instance: ctx.instance,
              organization: ctx.organization,
              performedBy: ctx.actor,
              serverId: ctx.body.server_id!,
              serverVariantId: ctx.body.server_variant_id,
              name: ctx.body.name,
              description: ctx.body.description,
              metadata: ctx.body.metadata,
              config: ctx.body.config
            });

        let magicMcpServer = await magicMcpServerService.createMagicMcpServer({
          organization: ctx.organization,
          performedBy: ctx.actor,
          instance: ctx.instance,
          context: ctx.context,
          input: {
            name: ctx.body.name,
            description: ctx.body.description,
            metadata: ctx.body.metadata,
            sessionTemplateId: sessionTemplate.id
          },
          consumer: ctx.consumerProfile ? { profile: ctx.consumerProfile } : undefined
        });

        return magicMcpServerPresenter.present({
          magicMcpServer: await withSessionTemplate(ctx, magicMcpServer)
        });
      }),

    delete: magicMcpServerGroup
      .delete(instancePath('magic-mcp-servers/:magicMcpServerId', 'magicMcpServers.delete'), {
        name: 'Delete magic MCP server',
        description: 'Delete a specific magic MCP server'
      })
      .use(
        checkAccess({
          possibleScopes: [
            'instance.server.deployment:write',
            'consumer#instance.magic_mcp:write'
          ]
        })
      )
      .output(magicMcpServerPresenter)
      .use(hasFlags(['magic-mcp-enabled']))
      .do(async ctx => {
        await magicMcpServerService.checkWriteAccess({
          server: ctx.magicMcpServer,
          accessTags: ctx.accessTags
        });

        let magicMcpServer = await magicMcpServerService.archiveMagicMcpServer({
          accessTags: ctx.accessTags,
          server: ctx.magicMcpServer
        });

        return magicMcpServerPresenter.present({
          magicMcpServer: await withSessionTemplate(ctx, magicMcpServer)
        });
      }),

    update: magicMcpServerGroup
      .patch(instancePath('magic-mcp-servers/:magicMcpServerId', 'magicMcpServers.update'), {
        name: 'Update magic MCP server',
        description: 'Update the information of a specific magic MCP server'
      })
      .use(
        checkAccess({
          possibleScopes: [
            'instance.server.deployment:write',
            'consumer#instance.magic_mcp:write'
          ]
        })
      )
      .body(
        'default',
        v.object({
          name: v.optional(v.string({ description: 'The name of the magic MCP server' })),
          description: v.optional(
            v.string({ description: 'The description of the magic MCP server' })
          ),
          metadata: v.optional(
            v.record(v.any(), { description: 'The metadata of the magic MCP server' })
          ),
          aliases: v.optional(
            v.array(v.string({ description: 'The alias (slug) of the magic MCP server' }))
          ),
          session_template_id: v.optional(
            v.string({
              description: 'The session template ID used to create/reuse the Subspace session'
            })
          )
        })
      )
      .output(magicMcpServerPresenter)
      .use(hasFlags(['magic-mcp-enabled']))
      .do(async ctx => {
        await magicMcpServerService.checkWriteAccess({
          server: ctx.magicMcpServer,
          accessTags: ctx.accessTags
        });

        let sessionTemplate = ctx.body.session_template_id
          ? await subspaceSessionTemplateService.get({
              instance: ctx.instance,
              organization: ctx.organization,
              sessionTemplateId: ctx.body.session_template_id
            })
          : undefined;

        let magicMcpServer = await magicMcpServerService.updateMagicMcpServer({
          server: ctx.magicMcpServer,
          accessTags: ctx.accessTags,
          input: {
            name: ctx.body.name,
            description: ctx.body.description,
            metadata: ctx.body.metadata,
            aliases: ctx.body.aliases,
            sessionTemplateId: sessionTemplate?.id
          }
        });

        return magicMcpServerPresenter.present({
          magicMcpServer: await withSessionTemplate(ctx, magicMcpServer)
        });
      })
  }
);
