name: 'Build and Push MCP Engine'

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main
  #     - dev
  #   paths:
  #     - 'src/mcp-engine/**'

jobs:
  build-and-push-mcp-engine:
    name: 'Build and Push MCP Engine'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service: [launcher, manager, remote, runner]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      SERVICE_NAME: metorial-mcp-engine-${{ matrix.service }}
      IMAGE_NAME: metorial/metorial-mcp-engine-${{ matrix.service }}
      DOCKERFILE: ./deployment/dockerfiles/engine-${{ matrix.service }}.Dockerfile
      REGISTRY: ghcr.io
      CONTAINER_TAG: mtoss-${{ github.ref_name }}-${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.SERVICE_NAME }}
            org.opencontainers.image.vendor=Metorial
          tags: |
            type=sha
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag,prefix=tag-
            type=ref,event=pr,prefix=pr-
            type=raw,value=${{ env.CONTAINER_TAG }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ env.DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
