name: 'Build and Push Deno Runner'

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - dev

jobs:
  build-and-push-deno-runner:
    name: 'Build and Push Deno Runner'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      SERVICE_NAME: metorial-deno-runner
      IMAGE_NAME: metorial/metorial-deno-runner
      DOCKERFILE: ./deployment/dockerfiles/deno-runner.Dockerfile
      REGISTRY: ghcr.io
      CONTAINER_TAG: mtoss-${{ github.ref_name }}-${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.SERVICE_NAME }}
            org.opencontainers.image.vendor=Metorial
          tags: |
            type=sha
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag,prefix=tag-
            type=ref,event=pr,prefix=pr-
            type=raw,value=${{ env.CONTAINER_TAG }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
