name: 'Build and Test'

on:
  workflow_dispatch:
  push:
    branches: [dev]
  pull_request:

jobs:
  build-and-test-ts:
    name: 'Build and Test TS'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_TOKEN || github.token }}
          fetch-depth: 0

      - name: Set up test workspace
        id: tests
        uses: ./.github/actions/setup-test-workspace
        with:
          tasks: test --filter=./src/metorial/packages/* --filter=./src/metorial/products/** --filter=./src/lowerdeck/** --filter=@metorial/nebula --filter=@metorial/function-bay --filter=@metorial/shuttle --filter=@metorial/slates --filter=@metorial/relay

      - name: Set up Warp Cache
        uses: ./.github/actions/setup-warp-cache
        with:
          aws-access-key-id: ${{ secrets.WARP_CACHE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.WARP_CACHE_AWS_SECRET_ACCESS_KEY }}
          signature-key: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
          role-arn: ${{ vars.WARP_CACHE_ROLE_ARN }}
          bucket: ${{ vars.WARP_CACHE_BUCKET }}

      - name: Test packages and services
        working-directory: ${{ steps.tests.outputs.workspace }}
        run: bunx turbo@2.9.18 run test --concurrency=2 --ui=stream --filter=./src/metorial/packages/* --filter=./src/metorial/products/** --filter=./src/lowerdeck/** --filter=@metorial/nebula --filter=@metorial/function-bay --filter=@metorial/shuttle --filter=@metorial/slates --filter=@metorial/relay

      - name: Test CI tooling
        working-directory: ${{ steps.tests.outputs.workspace }}
        run: bun test src/tooling/test-ci/*.test.ts

      - name: Report Warp Cache
        if: always()
        run: sh ./src/tooling/warp-cache/report.sh
