name: 'Build and Test'

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-and-test-ts:
    name: 'Build and Test TS'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Packages
        run: bun i

      - name: Generate Prisma Clients
        run: |
          bun x nx run-many --target=prisma:generate --all --parallel=1 \
            --exclude=@metorial/slates,@metorial/slates-registry,@metorial/synthesis,@metorial/ares,@metorial/forge,@metorial/function-bay,@metorial/signal,@metorial/cargo,@metorial/shuttle,@metorial/origin,@metorial/voyager,@metorial-subspace/app-public,@metorial-subspace/app-controller,@metorial-subspace/app-worker,@metorial-cargo/service,@metorial-cargo/db,@metorial-subspace/db
          bun x nx run @metorial-cargo/db:prisma:generate

      - name: Build Packages
        run: |
          bun x nx run-many --target=build --all --parallel=1 \
            --exclude=@metorial/slates,@metorial/slates-registry,@metorial/synthesis,@metorial/ares,@metorial/forge,@metorial/function-bay,@metorial/signal,@metorial/cargo,@metorial/shuttle,@metorial/origin,@metorial/voyager,@metorial-subspace/app-public,@metorial-subspace/app-controller,@metorial-subspace/app-worker,@metorial-cargo/service

      - name: Test
        run: |
          bun x nx run-many --target=test --all --parallel=1 \
            --exclude=@metorial/slates,@metorial/slates-registry,@metorial/synthesis,@metorial/ares,@metorial/forge,@metorial/function-bay,@metorial/signal,@metorial/cargo,@metorial/shuttle,@metorial/origin,@metorial/voyager,@metorial-subspace/app-public,@metorial-subspace/app-controller,@metorial-subspace/app-worker,@metorial-cargo/service
